### ISSUE TITLE
Adding backgrounds through the control panel

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-control-center#10]
<a href="https://github.com/eloc574"><img src="https://avatars.githubusercontent.com/u/5067255?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @eloc574**
_Saturday Sep 06, 2014 at 20:57 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/36_

---

I think it might be a good idea to implement the feature of dragging and dropping the pictures into the control panel backgrounds menu to add new backgrounds. This is used well under the boot menu background custimization and I actually assumed it was going to work like this when I was trying to add my own backgrounds because of this.

**Comment by manateelazycat** [comment]
We will make control center transparent in next version: deepin 15.4
So it's background will change along with desktop wallpaper

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
