### ISSUE TITLE
Custom Shortcut missing ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-control-center#101]
Hi,

My custom shortcuts have disappeared from the control center as a result the shortcut keys have stopped launching the configured commands ... however the file `/home/muz/.config/deepin/dde-daemon/keybinding/custom.ini` is very much present.

Is there any command that will kill and relaunch the control center ?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
