### ISSUE TITLE
Button to disable only animations

### ISSUE THREAD

**Issue by otavioschwanck** [linuxdeepin/dde-control-center#102]
We have only a way to disable Window Effect:
![image](https://user-images.githubusercontent.com/9551316/44620847-f6c9ef00-a871-11e8-89a9-f16dbb436dea.png)

But when disable it, we lose all the hardware acceleration, and lose a lot of performance.

Using dconf-editor, its possible to disable only window animations. 
![image](https://user-images.githubusercontent.com/9551316/44620854-12cd9080-a872-11e8-9aee-fcf5d7790902.png)

when disable only the windows animation, its possible to get a lot of performance (REALLY REALLY A LOT), without losing blur \ performance of hardware.

Mock:

![image](https://user-images.githubusercontent.com/9551316/44620889-bae35980-a872-11e8-9758-c283bc3a3296.png)

Only needs to set the com.deepin.wrap.pantheon.desktop.gala.animations.enabled-animations to false \ true.

Its super easy to do and super useful for new comers

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
