### ISSUE TITLE
ovpn file and stunnel, unsupported argument

### ISSUE THREAD

**Issue by haliliceylan** [linuxdeepin/dde-control-center#104]
Hi Guys,

I have ovpn file working with stunnel.

if I run command `sudo openvpn myconfig.ovpn`. Everything is fine and connection is working.

but i try to import ovpn file from control center. control center does not allowing me import to ovpn files.(it is only allowing .conf files)

then i run command `sudo nmcli connection import type openvpn file myconfig.ovpn` and i got this error
`Error: failed to import 'myconfig.ovpn': configuration error: unsupported 1th argument to “route” which looks like a FQDN but only IPv4 address supported (line 8).`

myconfig.ovpn file content is that.

```
client
nobind
dev tun
remote-cert-tls server

remote 127.0.0.1 1194 tcp
route <my-vpn-server-ip-replaced> 255.255.255.255 net_gateway
route 192.168.0.0 255.255.0.0 net_gateway
```

line 8 is `route <my-vpn-server-ip-replaced> 255.255.255.255 net_gateway`

according to me, this error is based on syntax `net_gateway`.

I had installed latest updates.

**Comment by haliliceylan** [comment]
I had using domain name on field `<my-vpn-server-ip-replaced>`. I switched to ip address instead of domain name.

new error is that 

`Error: failed to import 'myconfig.ovpn': configuration error: unsupported 3th argument net_gateway to “route” (line 8).`

**Comment by haliliceylan** [comment]
if is there anybody have the same issue try to run on command shell this command;
`sudo openvpn myconfig.ovpn`
if you have stunnel configuration run this;
`sudo systemctl start stunnel && sudo openvpn myconfig.ovpn`

**Comment by parsanoori** [comment]
I've got this problem. What did you do ?
