### ISSUE TITLE
[Feature request] Change anti-aliasing of fonts

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-control-center#106]
Deepin control center doesn't allow us to change the anti-aliasing of fonts.

Please add this feature as soon as pssible

**Comment by jouyouyun** [comment]
@zccrs

**Comment by SiamSami** [comment]
So, when is it coming?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
