### ISSUE TITLE
"natural scrolling" setting for touchpad not working

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-control-center#11]
<a href="https://github.com/xgdgsc"><img src="https://avatars.githubusercontent.com/u/1189869?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @xgdgsc**
_Wednesday Sep 10, 2014 at 12:15 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/42_

---

rt

**Comment by sbwtw** [comment]
fixed 15.4
