### ISSUE TITLE
Deepin 15.8 Control Center Feedback ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-control-center#110]
Hi,

While test driving Deepin 15.8 ... seems the new Control Center category design is not very appealing visually ... **the older tiled versions with widgets at the bottom was by faaaaaaaaaaaaar much more appealing** ... Sorry but his banner-tile implementation and **dropping of the widgets especially the Music widget is certainly a step backward in terms of a visually appealing interface** ...

You might want to consider reverting back to the previous tiled and music widget state ...

the wifi widget however could be dropped as at least i have NEVER used ... seems redundant and the work flow to use one from there was cumbersome compared to using it from the dock directly.

**Comment by SalahAdDin** [comment]
@aiamuzzi'm agreed with you, so much agree!!!

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
