### ISSUE TITLE
Adjusting scrolling speed doesn't work

### ISSUE THREAD

**Issue by pkaske** [linuxdeepin/dde-control-center#113]
I installed the latest version and to my excitement I saw that the control center now has a slider to adjust the scrolling speed for the mouse (I don't talk about the touchpad here)

I tried it but it doesn't change anything. ~/.imwheelrc is updated when I move the slider but scroll speed isn't changing in any application.

I had imwheel running manually before and now deepin has taken over with it's configuration. Now I'm stuck with very slow scrolling especially in chrome and vscode.

I use deepin desktop with manjaro.

What can I do?

**Comment by electricface** [comment]
is the imwheel running after adjust the scrolling speed?

**Comment by electricface** [comment]
I think you should set the scrolling speed to 1 in the deepin control center, write the imwheel configuration file and then automatically run imwheel in other ways.

**Comment by pkaske** [comment]
Ah ok, I can do that. Was hoping that setting scroll speed would finally be as easily as in other windows or macos. Thanks for helping. Appreciate it!
