### ISSUE TITLE
reboot-reminder-dialog path inconsistency

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/dde-control-center#115]
I build 4.9.4 with cmake on Fedora, reboot-reminder-dialog and dde-control-center are both installed to /usr/bin.

But in src/frame/modules/update/updatework.cpp, the absolute path of reboot-reminder-dialog is `/usr/lib/dde-control-center/reboot-reminder-dialog`.

**Comment by justforlxz** [comment]
The dde-control-center project switched from qmake to cmake, and installation path forgot to modify, Thanks for reminding.
