### ISSUE TITLE
[Antergoslinux] deepin-control-center 4.9.6-1 is broken

### ISSUE THREAD

**Issue by ganjaman666** [linuxdeepin/dde-control-center#117]
$ dde-control-center
dde-control-center: symbol lookup error: dde-control-center: undefined symbol: _ZNK3dde7network11WiredDevice28activeWiredConnectionChangedERK11QJsonObject

**Comment by felixonmars** [comment]
Please try again with deepin-control-center-4.9.6-2.

**Comment by ganjaman666** [comment]
> Please try again with deepin-control-center-4.9.6-2.

I've compiled dde-control-center from sorces (don't know what is the version number now) and it works now. Thank you for the hint.
