### ISSUE TITLE
[archlinux] deepin-control-center 4.9.6-1 is broken

### ISSUE THREAD

**Issue by alexnfsc175** [linuxdeepin/dde-control-center#118]
dde-control-center: symbol lookup error: dde-control-center: undefined symbol: _ZNK3dde7network11WiredDevice23activeConnectionChangedERK11QJsonObject

**Comment by felixonmars** [comment]
Please try again with deepin-control-center-4.9.6-2.

**Comment by alexnfsc175** [comment]
Thank you for your help

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
