### ISSUE TITLE
{Feature Request} Add support to select default file manager to control-center

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-control-center#12]
<a href="https://github.com/felixonmars"><img src="https://avatars.githubusercontent.com/u/1006477?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @felixonmars**
_Thursday Nov 26, 2015 at 04:16 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/130_

---

Currently double-clicking "Computer" will open Dolphin here for me, and I don't see a graphical way to change this. (Also Dolphin doesn't seem to handle `computer://`, so maybe even a blacklist could be implemented here?)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
