### ISSUE TITLE
icon theme is not properly displayed on Fedora

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/dde-control-center#120]
With version 4.9.4.

1. Icons of deepin theme is completely not displayed.
2. Icons of some themes are identical.

This may be a problem of packaging. But we need upstream help to fix it.

![Screenshot_fedora30-deepin_2019-03-14_12:33:14](https://user-images.githubusercontent.com/303331/54331623-c69f3d80-4655-11e9-945f-0af429364570.png)

![Screenshot_fedora30-deepin_2019-03-14_12:34:06](https://user-images.githubusercontent.com/303331/54331624-cbfc8800-4655-11e9-83f4-4f8c6dcdd488.png)

**Comment by justforlxz** [comment]
@electricface

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
