### ISSUE TITLE
图标主题对话框中的图标名称应当遵循 index.theme 配置中给定的显示名称

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/dde-control-center#1243]
此为由设计人员提出的问题。

当前：

![image](https://user-images.githubusercontent.com/10095765/221460351-76ee679b-e4ad-4782-a27c-0f7a1487fc95.png)

![image](https://user-images.githubusercontent.com/10095765/221460381-b47805cd-06e5-4cc9-a92a-857bf941002a.png)

期望：

显示为 index.theme 中给出的名称。

**Comment by wineee** [comment]
cursor.theme Name 没有 index.theme 规范，且此 issue 没有要求 cursor，cursor 主题暂时不动

**Comment by wineee** [comment]
![image](https://user-images.githubusercontent.com/22803888/223337995-f23cbdc4-a13a-474d-9725-cfb863d6864a.png)

**Comment by ComixHe** [comment]
dde-appearance的返回值不符合预期导致此错误

**Comment by wineee** [comment]
[dde-control-center_6.0.11_amd64.zip](https://github.com/linuxdeepin/dde-control-center/files/10906235/dde-control-center_6.0.11_amd64.zip)
(仅用于测试

**Comment by wineee** [comment]
> cursor

cursor 吗？预期是什么，cursor.theme 的 Name 本身似乎就不太规范

**Comment by ComixHe** [comment]
是指globalTheme,比如在index.theme中Name字段为`hazy color`，但是通过DBus返回的globalTheme是`hazy-color`

**Comment by wineee** [comment]
{"Comment":"","Deletable":false,"Example":"","Id":"bloom","Name":"bloom","Path":"/usr/share/icons/bloom","hasDark":false}

这个是我从 org.deepin.dde.Appearance1 的 List 读到的， Name 是对的

globalTheme 是指哪个接口？

**Comment by ComixHe** [comment]
刚才是我搞混了，这个行为应该是正确的:)

**Comment by xuqi27837288** [comment]
修复 by 修bug队，测试通过

**Comment by Decodetalkers** [comment]
fixed
