### ISSUE TITLE
"Tap to Click" option always enabled

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-control-center#13]
<a href="https://github.com/brendengibson"><img src="https://avatars.githubusercontent.com/u/8325533?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @brendengibson**
_Saturday Nov 28, 2015 at 02:36 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/136_

---

"Tap to Click" option always enabled even if setting in Control Center is turned off.

Was working properly in previous builds.

**Comment by sbwtw** [comment]
fixed at 15.4
