### ISSUE TITLE
can't set wallpaper

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-control-center#14]
<a href="https://github.com/zhuzilinuser"><img src="https://avatars.githubusercontent.com/u/12298476?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @zhuzilinuser**
_Friday Dec 11, 2015 at 04:48 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/173_

---

![20151211125026](https://cloud.githubusercontent.com/assets/12298476/11736150/c55db05e-a005-11e5-8c8b-52701c66a1c8.png)
![20151211125101](https://cloud.githubusercontent.com/assets/12298476/11736156/d934d684-a005-11e5-9e56-3307eecec0a5.png)

selete a photo to set wallpaper,but it just copy this file. dde-control-center not this wallpaper.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
