### ISSUE TITLE
Repeate items for the default timezone

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-control-center#15]
<a href="https://github.com/pavlanton"><img src="https://avatars.githubusercontent.com/u/16265783?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @pavlanton**
_Wednesday Dec 16, 2015 at 16:28 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/183_

---

![deepinscreenshot20151223214947](https://cloud.githubusercontent.com/assets/3049011/11977642/80930082-a9bf-11e5-9b2c-5f7c5ea9835d.png)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
