### ISSUE TITLE
autocreated gtk-theme preview

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-control-center#16]
<a href="https://github.com/oberon2007"><img src="https://avatars.githubusercontent.com/u/11800714?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @oberon2007**
_Monday Dec 21, 2015 at 23:08 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/196_

---

the preview thumbnails are created with black or white borders:
![windows](https://cloud.githubusercontent.com/assets/11800714/11943668/0a284c5c-a840-11e5-9d21-2ea70eb93b13.png)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
