### ISSUE TITLE
wifi-icon sometimes not showing connection (efficient mode)

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-control-center#17]
<a href="https://github.com/oberon2007"><img src="https://avatars.githubusercontent.com/u/11800714?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @oberon2007**
_Wednesday Dec 23, 2015 at 14:17 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/200_

---

with present and working wifi connection, sometimes the icon is showing 'no connection':
![wifi](https://cloud.githubusercontent.com/assets/11800714/11978004/3f7f6360-a988-11e5-90d7-a2ac84123c00.png)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
