### ISSUE TITLE
Control center doesn't disappear once opened - Deepin installed as ubuntu enviroment

### ISSUE THREAD

**Issue by BendeRobert** [linuxdeepin/dde-control-center#173]
Hi, I've just recently installed Deepin as an enviroment on my Ubuntu. Everything seems to be working just fine, but once I open the control center it doesn't really close. I guess it should be closing when I click an element outside of the control center box. It doesn't. Or when I press the ESC key or something, it doesn't either. I've searched for this problem online, and some guys claim that they solved it by forwarding the deepin api to the latest version.. well i dont really know how to do that on using ubuntu related commands so I would very much appreciate any help towards solving this problem.

**Comment by hualet** [comment]
DDE on Ubuntu is not being maintained anymore, so there're bugs that we can't fix.

Debian is packaging DDE, maybe you can use DDE until then?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
