### ISSUE TITLE
When a character is not a alphabet was used in the keyboard settings, problem occurs in the list

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-control-center#18]
<a href="https://github.com/fu-sen"><img src="https://avatars.githubusercontent.com/u/5434159?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @fu-sen**
_Saturday Dec 26, 2015 at 08:46 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/202_

---

I tried Deepin flavor of Manjaro in Japanese.
I looked for "日本語" (Japanese) from the list of "J" in the setting of the keyboard, but it did not exist.
As a result of looking for the list, it had been included in the why "R".
When it is in the language is not in English, it seems to have a problem with the sort of keyboard settings.

![list of "J"](https://cloud.githubusercontent.com/assets/5434159/12005735/5ecbd90c-abf8-11e5-83bf-f1fdf330b6fb.jpg)

![list of "R" 1](https://cloud.githubusercontent.com/assets/5434159/12005736/64a9e21a-abf8-11e5-8498-4d9219e2fac5.jpg)

![list of "R" 2](https://cloud.githubusercontent.com/assets/5434159/12005738/68737aa0-abf8-11e5-8494-8fc8f60818c1.jpg)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
