### ISSUE TITLE
鼠标移动到显示-自定义设置时自动注销

### ISSUE THREAD

**Issue by AppJ-GS** [linuxdeepin/dde-control-center#182]
1. 问题/建议描述
鼠标一移动到显示设置里就自动注销
2. 问题如何重现
打开控制中心-显示
3. 问题重现频率
100%
[deepin-feedback-cli-Deepin-15.10-all-20190501-120216.tar.gz](https://github.com/linuxdeepin/dde-control-center/files/3133824/deepin-feedback-cli-Deepin-15.10-all-20190501-120216.tar.gz)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
