### ISSUE TITLE
[Arch Linux] Change Time Settings Shows Wrong Time In The Analog Clock

### ISSUE THREAD

**Issue by praveenpious** [linuxdeepin/dde-control-center#187]
![image](https://user-images.githubusercontent.com/44629680/57472107-861d0400-7241-11e9-96fb-c9d1d564ff18.png)

The image explains the bug. The actual time is 09:58. But the analog clock shows 08:58. Please look into it. The distribution is Arch Linux.

**Comment by justforlxz** [comment]
Does your time zone have daylight saving time?

**Comment by praveenpious** [comment]
Yes it does.

**Comment by eperulli** [comment]
Same here, with latest ArchLinux, fresh install.
Modifying rhe rtc clock via bios, using timdatectl or hwclock doesn't work.
The analog clock is an hour behind.
![DeepinScreenshot_seleziona-area_20190621215849](https://user-images.githubusercontent.com/52085800/59948342-0903c200-9470-11e9-9fc9-aa830b9aa1b9.png)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
