### ISSUE TITLE
popup of bluetooth applet is too high sometimes

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-control-center#19]
<a href="https://github.com/felixonmars"><img src="https://avatars.githubusercontent.com/u/1006477?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @felixonmars**
_Monday Jan 04, 2016 at 06:14 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/220_

---

![2016-01-04-141302-911099](https://cloud.githubusercontent.com/assets/1006477/12084372/765d6260-b2ed-11e5-8ade-d60065f02315.png)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
