### ISSUE TITLE
编译时遇到问题

### ISSUE THREAD

**Issue by MCredbear** [linuxdeepin/dde-control-center#195]
dpkg-buildpackage检查过依赖了，都装齐了，发行版是debian sid arm64
```
[ 49%] Building CXX object src/frame/CMakeFiles/dde-control-center.dir/modules/display/miracastmodel.cpp.o
cd /dev/dde-control-center/obj-aarch64-linux-gnu/src/frame && /usr/bin/c++  -DDEEPIN_DDE -DDISABLE_POWER -DDISABLE_SYS_UPDATE_MIRRORS -DDISABLE_SYS_UPDATE_SOURCE_CHECK -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQ_HOST_AARCH64 -DQ_HOST_NAME=\"aarch64\" -DQ_OS_DEBIAN -DQ_OS_DEEPIN_DESKTOP -DQ_OS_DEEPIN_VERSION=\"15.10\" -DQ_OS_VERSION=\"10\" -I/dev/dde-control-center/obj-aarch64-linux-gnu/src/frame -I/dev/dde-control-center/src/frame -I/dev/dde-control-center/obj-aarch64-linux-gnu/src/frame/dde-control-center_autogen/include -I/usr/include/libdtk-2.0.9/DCore -I/usr/include/libdtk-2.0.9/DCore/../DWidget -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/aarch64-linux-gnu/qt5/QtGui/5.11.3 -I/usr/include/aarch64-linux-gnu/qt5/QtGui/5.11.3/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore/5.11.3 -I/usr/include/aarch64-linux-gnu/qt5/QtCore/5.11.3/QtCore -I/dev/dde-control-center/obj-aarch64-linux-gnu -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/libddenetworkutils -I/opt/gstreamer/include/glib-2.0 -I/opt/gstreamer/lib/glib-2.0/include -I/usr/include/libnm -I/usr/include/KF5/NetworkManagerQt -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/KF5 -isystem /usr/include/aarch64-linux-gnu/qt5 -isystem /usr/include/aarch64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/aarch64-linux-gnu/qt5/QtGui -isystem /usr/include/aarch64-linux-gnu/qt5/QtCore -isystem /usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/aarch64-linux-gnu/qt5/QtWidgets -isystem /usr/include/aarch64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/aarch64-linux-gnu/qt5/QtDBus -isystem /usr/include/aarch64-linux-gnu/qt5/QtNetwork -isystem /usr/include/aarch64-linux-gnu/qt5/QtMultimedia  -g -Wall   -fPIC -std=gnu++14 -o CMakeFiles/dde-control-center.dir/modules/display/miracastmodel.cpp.o -c /dev/dde-control-center/src/frame/modules/display/miracastmodel.cpp
/dev/dde-control-center/src/frame/modules/display/displayworker.cpp: In member function ‘void dcc::display::DisplayWorker::active()’:
/dev/dde-control-center/src/frame/modules/display/displayworker.cpp:103:99: error: ‘using AppearanceInter = com::deepin::daemon::Appearance’ {aka ‘class __Appearance’} has no member named ‘GetScreenScaleFactors’; did you mean ‘GetScaleFactor’?
     QDBusPendingCallWatcher *screenscaleswatcher = new QDBusPendingCallWatcher(m_appearanceInter->GetScreenScaleFactors());
                                  ^~~~~~~~~~~~~~~~~~~~~
                                  GetScaleFactor
/dev/dde-control-center/src/frame/modules/display/displayworker.cpp: In member function ‘void dcc::display::DisplayWorker::setIndividualScaling(dcc::display::Monitor*, double)’:
/dev/dde-control-center/src/frame/modules/display/displayworker.cpp:395:24: error: ‘using AppearanceInter = com::deepin::daemon::Appearance’ {aka ‘class __Appearance’} has no member named ‘SetScreenScaleFactors’; did you mean ‘SetScaleFactor’?
     m_appearanceInter->SetScreenScaleFactors(scalemap);
                        ^~~~~~~~~~~~~~~~~~~~~
                        SetScaleFactor
```

**Comment by justforlxz** [comment]
libdframeworkdbus-dev的版本？

**Comment by MCredbear** [comment]
1.1.0-2

**Comment by justforlxz** [comment]
> 1.1.0-2

你需要1.1.1版本。

**Comment by BLumia** [comment]
> 1.1.1的版本在哪里获取？我看了deepin的测试版仓库也是1.1.0的

内测仓库是个临时仓库，换回主仓库试试？

以及如果你的源码是从 GitHub 获取的话，可以[直接看打了哪些 tag](https://github.com/linuxdeepin/dde-qt-dbus-factory/tags) 。

**Comment by MCredbear** [comment]
主仓库地址能给一个吗？我好像没找到

**Comment by MCredbear** [comment]
好的，谢谢

**Comment by MCredbear** [comment]
但是为什么打了tag的1.1.1和1.1.2编译出来的libdframeworkdbus-dev版本更低只有0.4.2?

**Comment by MCredbear** [comment]
又遇到问题了

In file included from /usr/include/aarch64-linux-gnu/qt5/QtCore/qnamespace.h:43,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qobjectdefs.h:48,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qobject.h:46,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/QObject:1,
                 from /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundworker.h:29,
                 from /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundworker.cpp:26:
/usr/include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h: In instantiation of ‘constexpr int qMetaTypeId() [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’:
/usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:719:43:   required from ‘static T QtPrivate::QVariantValueHelper<T>::metaType(const QVariant&) [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’
/usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:115:37:   required from ‘static ReturnType QtPrivate::MetaTypeInvoker<Derived, Argument, ReturnType>::invoke(Argument) [with Derived = QtPrivate::QVariantValueHelper<Dtk::Widget::DDesktopServices::SystemSoundEffect>; Argument = const QVariant&; ReturnType = Dtk::Widget::DDesktopServices::SystemSoundEffect ’
/usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:858:62:   required from ‘T qvariant_cast(const QVariant&) [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’
/usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:362:30:   required from ‘T QVariant::value() const [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’
/media/firefly/dde/dde-control-center/src/frame/modules/sound/soundworker.cpp:333:82:   required from here
/usr/include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h:1769:5: error: static assertion failed: Type is not registered, please use the Q_DECLARE_METATYPE macro to make it known to Qt's meta-object system
     Q_STATIC_ASSERT_X(QMetaTypeId2<T>::Defined, "Type is not registered, please use the Q_DECLARE_METATYPE macro to make it known to Qt's meta-object system");
     ^~~~~~~~~~~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/qt5/QtCore/qobject.h:54,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/QObject:1,
                 from /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundworker.h:29,
                 from /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundworker.cpp:26:
/usr/include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h: In instantiation of ‘static constexpr int QMetaTypeId2<T>::qt_metatype_id() [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’:
/usr/include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h:1770:43:   required from ‘static T QtPrivate::QVariantValueHelper<T>::metaType(const QVariant&) [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’
/usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:115:37:   required from ‘static ReturnType QtPrivate::MetaTypeInvoker<Derived, Argument, ReturnType>::invoke(Argument) [with Derived = QtPrivate::QVariantValueHelper<Dtk::Widget::DDesktopServices::SystemSoundEffect>; Argument = const QVariant&; ReturnType = Dtk::Widget::DDesktopServices::SystemSoundEffect ’
/usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:858:62:   required from ‘T qvariant_cast(const QVariant&) [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’
/usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:362:30:   required from ‘T QVariant::value() const [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’
/media/firefly/dde/dde-control-center/src/frame/modules/sound/soundworker.cpp:333:82:   required from here
/usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:719:43:   in ‘constexpr’ expansion of ‘qMetaTypeId<Dtk::Widget::DDesktopServices::SystemSoundEffect>()’
/usr/include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h:1634:96: error: ‘qt_metatype_id’ is not a member of ‘QMetaTypeId<Dtk::Widget::DDesktopServices::SystemSoundEffect>’
     static inline Q_DECL_CONSTEXPR int qt_metatype_id() { return QMetaTypeId<T>::qt_metatype_id(); }
                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
[ 79%] Building CXX object src/frame/CMakeFiles/dde-control-center.dir/modules/sound/soundwidget.cpp.o
cd /media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu/src/frame && /usr/bin/c++  -DDEEPIN_DDE -DDISABLE_POWER -DDISABLE_SYS_UPDATE_MIRRORS -DDISABLE_SYS_UPDATE_SOURCE_CHECK -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQ_HOST_AARCH64 -DQ_HOST_NAME=\"aarch64\" -DQ_OS_DEBIAN -DQ_OS_DEEPIN_DESKTOP -DQ_OS_DEEPIN_VERSION=\"15.10\" -DQ_OS_VERSION=\"10\" -I/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu/src/frame -I/media/firefly/dde/dde-control-center/src/frame -I/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu/src/frame/dde-control-center_autogen/include -I/usr/include/libdtk-2.0.9/DCore -I/usr/include/libdtk-2.0.9/DCore/../DWidget -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/aarch64-linux-gnu/qt5/QtGui/5.11.3 -I/usr/include/aarch64-linux-gnu/qt5/QtGui/5.11.3/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore/5.11.3 -I/usr/include/aarch64-linux-gnu/qt5/QtCore/5.11.3/QtCore -I/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/libddenetworkutils -I/opt/gstreamer/include/glib-2.0 -I/opt/gstreamer/lib/glib-2.0/include -I/usr/include/libnm -I/usr/include/KF5/NetworkManagerQt -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/KF5 -isystem /usr/include/aarch64-linux-gnu/qt5 -isystem /usr/include/aarch64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/aarch64-linux-gnu/qt5/QtGui -isystem /usr/include/aarch64-linux-gnu/qt5/QtCore -isystem /usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/aarch64-linux-gnu/qt5/QtWidgets -isystem /usr/include/aarch64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/aarch64-linux-gnu/qt5/QtDBus -isystem /usr/include/aarch64-linux-gnu/qt5/QtNetwork -isystem /usr/include/aarch64-linux-gnu/qt5/QtMultimedia  -g -Wall   -fPIC -std=gnu++14 -o CMakeFiles/dde-control-center.dir/modules/sound/soundwidget.cpp.o -c /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundwidget.cpp
[ 79%] Building CXX object src/frame/CMakeFiles/dde-control-center.dir/modules/sound/soundeffectpage.cpp.o
cd /media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu/src/frame && /usr/bin/c++  -DDEEPIN_DDE -DDISABLE_POWER -DDISABLE_SYS_UPDATE_MIRRORS -DDISABLE_SYS_UPDATE_SOURCE_CHECK -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQ_HOST_AARCH64 -DQ_HOST_NAME=\"aarch64\" -DQ_OS_DEBIAN -DQ_OS_DEEPIN_DESKTOP -DQ_OS_DEEPIN_VERSION=\"15.10\" -DQ_OS_VERSION=\"10\" -I/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu/src/frame -I/media/firefly/dde/dde-control-center/src/frame -I/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu/src/frame/dde-control-center_autogen/include -I/usr/include/libdtk-2.0.9/DCore -I/usr/include/libdtk-2.0.9/DCore/../DWidget -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/aarch64-linux-gnu/qt5/QtGui/5.11.3 -I/usr/include/aarch64-linux-gnu/qt5/QtGui/5.11.3/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore/5.11.3 -I/usr/include/aarch64-linux-gnu/qt5/QtCore/5.11.3/QtCore -I/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/libddenetworkutils -I/opt/gstreamer/include/glib-2.0 -I/opt/gstreamer/lib/glib-2.0/include -I/usr/include/libnm -I/usr/include/KF5/NetworkManagerQt -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/KF5 -isystem /usr/include/aarch64-linux-gnu/qt5 -isystem /usr/include/aarch64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/aarch64-linux-gnu/qt5/QtGui -isystem /usr/include/aarch64-linux-gnu/qt5/QtCore -isystem /usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/aarch64-linux-gnu/qt5/QtWidgets -isystem /usr/include/aarch64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/aarch64-linux-gnu/qt5/QtDBus -isystem /usr/include/aarch64-linux-gnu/qt5/QtNetwork -isystem /usr/include/aarch64-linux-gnu/qt5/QtMultimedia  -g -Wall   -fPIC -std=gnu++14 -o CMakeFiles/dde-control-center.dir/modules/sound/soundeffectpage.cpp.o -c /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundeffectpage.cpp
make[3]: *** [src/frame/CMakeFiles/dde-control-center.dir/build.make:4517: src/frame/CMakeFiles/dde-control-center.dir/modules/sound/soundworker.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:96: src/frame/CMakeFiles/dde-control-center.dir/all] Error 2
make[2]: Leaving directory '/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu'
make[1]: *** [Makefile:133: all] Error 2
make[1]: Leaving directory '/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu'
dh_auto_build: cd obj-aarch64-linux-gnu && make -j4 returned exit code 2make: *** [debian/rules:11: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
firefly@firefly:/media/firefly/dde/dde-control-center$

**Comment by hillwoodroc** [comment]
在 openSUSE 确认这个错误。

**Comment by hillwoodroc** [comment]
> 又遇到问题了
> 
> In file included from /usr/include/aarch64-linux-gnu/qt5/QtCore/qnamespace.h:43,
> from /usr/include/aarch64-linux-gnu/qt5/QtCore/qobjectdefs.h:48,
> from /usr/include/aarch64-linux-gnu/qt5/QtCore/qobject.h:46,
> from /usr/include/aarch64-linux-gnu/qt5/QtCore/QObject:1,
> from /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundworker.h:29,
> from /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundworker.cpp:26:
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h: In instantiation of ‘constexpr int qMetaTypeId() [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’:
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:719:43: required from ‘static T QtPrivate::QVariantValueHelper::metaType(const QVariant&) [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:115:37: required from ‘static ReturnType QtPrivate::MetaTypeInvoker<Derived, Argument, ReturnType>::invoke(Argument) [with Derived = QtPrivate::QVariantValueHelperDtk::Widget::DDesktopServices::SystemSoundEffect; Argument = const QVariant&; ReturnType = Dtk::Widget::DDesktopServices::SystemSoundEffect ’
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:858:62: required from ‘T qvariant_cast(const QVariant&) [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:362:30: required from ‘T QVariant::value() const [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’
> /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundworker.cpp:333:82: required from here
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h:1769:5: error: static assertion failed: Type is not registered, please use the Q_DECLARE_METATYPE macro to make it known to Qt's meta-object system
> Q_STATIC_ASSERT_X(QMetaTypeId2::Defined, "Type is not registered, please use the Q_DECLARE_METATYPE macro to make it known to Qt's meta-object system");
> ^~~~~~~~~~~~~~~~~
> In file included from /usr/include/aarch64-linux-gnu/qt5/QtCore/qobject.h:54,
> from /usr/include/aarch64-linux-gnu/qt5/QtCore/QObject:1,
> from /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundworker.h:29,
> from /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundworker.cpp:26:
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h: In instantiation of ‘static constexpr int QMetaTypeId2::qt_metatype_id() [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’:
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h:1770:43: required from ‘static T QtPrivate::QVariantValueHelper::metaType(const QVariant&) [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:115:37: required from ‘static ReturnType QtPrivate::MetaTypeInvoker<Derived, Argument, ReturnType>::invoke(Argument) [with Derived = QtPrivate::QVariantValueHelperDtk::Widget::DDesktopServices::SystemSoundEffect; Argument = const QVariant&; ReturnType = Dtk::Widget::DDesktopServices::SystemSoundEffect ’
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:858:62: required from ‘T qvariant_cast(const QVariant&) [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:362:30: required from ‘T QVariant::value() const [with T = Dtk::Widget::DDesktopServices::SystemSoundEffect]’
> /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundworker.cpp:333:82: required from here
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:719:43: in ‘constexpr’ expansion of ‘qMetaTypeIdDtk::Widget::DDesktopServices::SystemSoundEffect()’
> /usr/include/aarch64-linux-gnu/qt5/QtCore/qmetatype.h:1634:96: error: ‘qt_metatype_id’ is not a member of ‘QMetaTypeIdDtk::Widget::DDesktopServices::SystemSoundEffect’
> static inline Q_DECL_CONSTEXPR int qt_metatype_id() { return QMetaTypeId::qt_metatype_id(); }
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
> [ 79%] Building CXX object src/frame/CMakeFiles/dde-control-center.dir/modules/sound/soundwidget.cpp.o
> cd /media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu/src/frame && /usr/bin/c++ -DDEEPIN_DDE -DDISABLE_POWER -DDISABLE_SYS_UPDATE_MIRRORS -DDISABLE_SYS_UPDATE_SOURCE_CHECK -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQ_HOST_AARCH64 -DQ_HOST_NAME="aarch64" -DQ_OS_DEBIAN -DQ_OS_DEEPIN_DESKTOP -DQ_OS_DEEPIN_VERSION="15.10" -DQ_OS_VERSION="10" -I/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu/src/frame -I/media/firefly/dde/dde-control-center/src/frame -I/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu/src/frame/dde-control-center_autogen/include -I/usr/include/libdtk-2.0.9/DCore -I/usr/include/libdtk-2.0.9/DCore/../DWidget -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/aarch64-linux-gnu/qt5/QtGui/5.11.3 -I/usr/include/aarch64-linux-gnu/qt5/QtGui/5.11.3/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore/5.11.3 -I/usr/include/aarch64-linux-gnu/qt5/QtCore/5.11.3/QtCore -I/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/libddenetworkutils -I/opt/gstreamer/include/glib-2.0 -I/opt/gstreamer/lib/glib-2.0/include -I/usr/include/libnm -I/usr/include/KF5/NetworkManagerQt -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/KF5 -isystem /usr/include/aarch64-linux-gnu/qt5 -isystem /usr/include/aarch64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/aarch64-linux-gnu/qt5/QtGui -isystem /usr/include/aarch64-linux-gnu/qt5/QtCore -isystem /usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/aarch64-linux-gnu/qt5/QtWidgets -isystem /usr/include/aarch64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/aarch64-linux-gnu/qt5/QtDBus -isystem /usr/include/aarch64-linux-gnu/qt5/QtNetwork -isystem /usr/include/aarch64-linux-gnu/qt5/QtMultimedia -g -Wall -fPIC -std=gnu++14 -o CMakeFiles/dde-control-center.dir/modules/sound/soundwidget.cpp.o -c /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundwidget.cpp
> [ 79%] Building CXX object src/frame/CMakeFiles/dde-control-center.dir/modules/sound/soundeffectpage.cpp.o
> cd /media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu/src/frame && /usr/bin/c++ -DDEEPIN_DDE -DDISABLE_POWER -DDISABLE_SYS_UPDATE_MIRRORS -DDISABLE_SYS_UPDATE_SOURCE_CHECK -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQ_HOST_AARCH64 -DQ_HOST_NAME="aarch64" -DQ_OS_DEBIAN -DQ_OS_DEEPIN_DESKTOP -DQ_OS_DEEPIN_VERSION="15.10" -DQ_OS_VERSION="10" -I/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu/src/frame -I/media/firefly/dde/dde-control-center/src/frame -I/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu/src/frame/dde-control-center_autogen/include -I/usr/include/libdtk-2.0.9/DCore -I/usr/include/libdtk-2.0.9/DCore/../DWidget -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/aarch64-linux-gnu/qt5/QtGui/5.11.3 -I/usr/include/aarch64-linux-gnu/qt5/QtGui/5.11.3/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore/5.11.3 -I/usr/include/aarch64-linux-gnu/qt5/QtCore/5.11.3/QtCore -I/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu -I/usr/include/aarch64-linux-gnu/qt5/QGSettings -I/usr/include/libddenetworkutils -I/opt/gstreamer/include/glib-2.0 -I/opt/gstreamer/lib/glib-2.0/include -I/usr/include/libnm -I/usr/include/KF5/NetworkManagerQt -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/KF5 -isystem /usr/include/aarch64-linux-gnu/qt5 -isystem /usr/include/aarch64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/aarch64-linux-gnu/qt5/QtGui -isystem /usr/include/aarch64-linux-gnu/qt5/QtCore -isystem /usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/aarch64-linux-gnu/qt5/QtWidgets -isystem /usr/include/aarch64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/aarch64-linux-gnu/qt5/QtDBus -isystem /usr/include/aarch64-linux-gnu/qt5/QtNetwork -isystem /usr/include/aarch64-linux-gnu/qt5/QtMultimedia -g -Wall -fPIC -std=gnu++14 -o CMakeFiles/dde-control-center.dir/modules/sound/soundeffectpage.cpp.o -c /media/firefly/dde/dde-control-center/src/frame/modules/sound/soundeffectpage.cpp
> make[3]: *** [src/frame/CMakeFiles/dde-control-center.dir/build.make:4517: src/frame/CMakeFiles/dde-control-center.dir/modules/sound/soundworker.cpp.o] Error 1
> make[3]: *** Waiting for unfinished jobs....
> make[3]: Leaving directory '/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu'
> make[2]: *** [CMakeFiles/Makefile2:96: src/frame/CMakeFiles/dde-control-center.dir/all] Error 2
> make[2]: Leaving directory '/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu'
> make[1]: *** [Makefile:133: all] Error 2
> make[1]: Leaving directory '/media/firefly/dde/dde-control-center/obj-aarch64-linux-gnu'
> dh_auto_build: cd obj-aarch64-linux-gnu && make -j4 returned exit code 2make: *** [debian/rules:11: build] Error 2
> dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
> firefly@firefly:/media/firefly/dde/dde-control-center$

你简单粗暴的把 src/frame/modules/sound/soundworker.h 里面的
```
// should include 2.0.9.17
#if DTK_VERSION < DTK_VERSION_CHECK(2, 0, 9, 17)
    Q_DECLARE_METATYPE(DDesktopServices::SystemSoundEffect)
#endif
```
删除就解决了。

**Comment by BLumia** [comment]
cc @justforlxz

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
