### ISSUE TITLE
Feature Request: Get the control center in a dedicated window

### ISSUE THREAD

**Issue by xakraz** [linuxdeepin/dde-control-center#199]
I really appreciate the Deepin side panel as much as the one from Budgie Desktop / SolusOS.

However, I would rather have only the notifications and some widgets in the side panel like macOS does.

Having a dedicated window, centered for settings is something that users are more used to in terms of UX.

**Comment by BLumia** [comment]
It's planned in the next major version update :)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
