### ISSUE TITLE
AutoPlay Feature Not Working

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-control-center#21]
<a href="https://github.com/stevedude"><img src="https://avatars.githubusercontent.com/u/8483863?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @stevedude**
_Thursday Feb 04, 2016 at 20:28 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/239_

---

I am using Manjaro Deepin 15.12, 64-bit, 4.1 kernel, NVidia GTS 450 Grpahics Card, AMD Phenom II Processor.

My issue is that AutoPlay does not seem to work.  The setting for the Control Center is set to autoplay CDs and DVDs with their associated programs, but when I insert an optical disk, nothing happens. I have to launch my program manually in order to play the material.

Thanks

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
