### ISSUE TITLE
touchscreen settings missing

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-control-center#22]
<a href="https://github.com/femans"><img src="https://avatars.githubusercontent.com/u/625851?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @femans**
_Tuesday Feb 23, 2016 at 09:17 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/250_

---

in the settings panel is no section for the touchscreen. There isnt one for the trackpoint either.
I would expect these at the mouse/touchpad settings.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
