### ISSUE TITLE
[archlinux] impossible to enter WIFI password

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-control-center#23]
When selecting a new network in the control center, the box for entering the password is displayed very briefly, but then the control center immediately closes and I have now way to enter the password. Selecting the same network again has no effect.
The only way to login I could find in the end was to log out and back in so a separate dialog window for the password would appear on the desktop. 
I'm running **deepin-control-center 3.0.11**

**Comment by fasheng** [comment]
Looks the dde-control-center hidden at the moment you entering the password. And it's not only just network, I could reproduct it by pressing any module it left side in dde-control-center. I remember @felixonmars and @iceleaf916 disccussed it before, any progress?

BTW: for this issue, a temprorary solution is active SSID from dock-applet and it will popup a dialog to enter password...

**Comment by fasheng** [comment]
We solved it just now, wait for the next minor release, please.
