### ISSUE TITLE
Brightness control broken

### ISSUE THREAD

**Issue by trading-peter** [linuxdeepin/dde-control-center#230]
Since the update to Deepin Control Center 4.10.8-1 brightness control is broken.

State before the update:
I'm using a laptop with one external monitor connected. Before the update brightness control with the function keys and with the slider in the control center was working fine for the laptops internal screen. The brightness of the external monitor couldn't be control (slider showed up but didn't have an effect) which was totally fine because they have hardware controls anyway for that.

State now after update to 4.10.8-1
Both sliders work for both displays but the brightness setting doesn't stick. It falls back after a few seconds. Often to a ridiculous dark setting. The slider gui control itself stays where it was set to. I then have to reboot my machine and hope that it will use a more usable "default" to that I can work with it.

I recorded a video to demonstrate the behavior:
https://photos.app.goo.gl/qVD4VDXUJYWoD42Z9

I'm on Majaro 64bit with nvidia drivers.

**Comment by BLumia** [comment]
@justforlxz @electricface

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
