### ISSUE TITLE
[archlinux] pkg without updater?

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-control-center#25]
@felixonmars would you consider building archlinux **deepin-control-center** pkg with option ``WITH_MODULE_SYSINFO_UPDATE=NO`` ?
This will supply a perfectly functional system-info widget including the licence display but without the updater, which is useless and confusing for the user in Archlinux :wink:

**Comment by oberon2007** [comment]
:smile:

![system_info](https://cloud.githubusercontent.com/assets/11800714/15877139/1d05d374-2d12-11e6-8bd0-58967c26adae.jpg)

**Comment by felixonmars** [comment]
Sounds a good idea to me :)

Implemented in 3.0.13-2.

**Comment by oberon2007** [comment]
Great! Thank you. :+1:
