### ISSUE TITLE
@emhaye as an alternative to the `Use this connection only for resources on its network` option you can try using this command:

### ISSUE THREAD

**Issue by bistungki** [linuxdeepin/dde-control-center#254]
@emhaye as an alternative to the `Use this connection only for resources on its network` option you can try using this command:
`$ sudo nmcli connection modify <your_connection_name> ipv4.never-default true`

_Originally posted by @ghost in https://github.com/linuxdeepin/dde-control-center/issues/43#issuecomment-321680972_

**Comment by BLumia** [comment]
Maybe you can reply in that issue directly? :joy:
