### ISSUE TITLE
Notifications in control center are not interactive

### ISSUE THREAD

**Issue by jonnypetraglia** [linuxdeepin/dde-control-center#256]
If I open the notification list, clicking the notification does not open the application. All it does is display text, and let you dismiss it. I would expect it (just like in macOS) to open up the application, just as the notification does when it initially pops up. Without this, it's nice, but not really all that helpful. It seems like if I can click the notification when it initially pops up, I should also be able to click it in the notification list.

I'm running Deepin 15.10.2

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
