### ISSUE TITLE
When there is only one bluetooth host, skip selection

### ISSUE THREAD

**Issue by ralsina** [linuxdeepin/dde-control-center#257]
Currently if I want to connect to a BT device, I have to:

1. click on the control center icon
2. click on "bluetooth"
3. click on my hostname
4. choose the device

Step 3 serves no purpose because I only have one BT controller, like almost all users. So, when there is only one, that step should be omitted and just jump from step 2 to step 4

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
