### ISSUE TITLE
Power Management Does not Powersave

### ISSUE THREAD

**Issue by bksubhuti** [linuxdeepin/dde-control-center#259]
Powermanagement does not do powersave and performance on  the cpu.

cpufrequtils is not installed
I have to do this..in order to do real powersave 

 `sudo cpupower frequency-set --governor powersave`

to turn it back on .. 
`sudo cpupower frequency-set --governor performance`

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
