### ISSUE TITLE
Cannot connect modem Huawei E220 on Deepin 15.2

### ISSUE THREAD

**Issue by fortezhuo** [linuxdeepin/dde-control-center#26]
Deepin 15.2 can detect my modem Huawei E220 as "Huawei Technologies E220 HSDPA Modem" , but only offer an irresponsive link "Restore the connection > ". While I click this link, nothing happend

**Comment by fasheng** [comment]
Sorry for the trouble, p
lease install the missing package mobile-broadband-provider-info, we fixed the dependency a few time ago but may not sync it to public repo.

**Comment by hedikasmanto** [comment]
Thanks for your quick reply. After I installed mobile-broadband-provider-info. It seems to be "connected" but not stable. And notification box inform the device was removed. And currently, I live in Indonesia, and use Indonesian provider. Can I add or edit selected plan ?

**Comment by fasheng** [comment]
Hou about editing the connection by clicking the right `>` button to custom your mobile plan?

**Comment by hedikasmanto** [comment]
thanks for your reply. But I can't custom through control-center due to system detect my modem very unstable. While I try to custom, suddenly notification box displayed and inform the modem was removed.  If I wait for few minutes, system can detect that modem again and but later same pop up will be displayed and inform the modem was removed again.

**Comment by fasheng** [comment]
I'm afraid it's driver/usb-modeswitch related problem. Please run the command to collect some syslog after the modem plugged:
journalctl -f

And the usb device details with:
lsusb



2016年7月14日 21:42, 21:42，在 Hedi Kasmanto <notifications@github.com> 已写:

**Comment by fasheng** [comment]
And what happed if you run 'mmcli -M'?

**Comment by hedikasmanto** [comment]
Thanks for your quick reply. Here I have run command that you suggested.

forte@ideapad:~$ journalctl -f
-- Logs begin at Fri 2016-07-15 08:20:14 ICT. --
Jul 15 08:20:44 ideapad com.deepin.daemon.Audio[986]: <info> manager_device.go:242: add device &network.device{nmDev:(*networkmanager.Device)(0xc8202e21e0), nmDevWireless:(*networkmanager.DeviceWireless)(nil), mmDevModem:(*modemmanager1.Modem)(nil), nmDevType:0x5, id:"1C:77:F6:E2:B3:4C", udi:"/org/bluez/hci0/dev_1C_77_F6_E2_B3_4C", Path:"/org/freedesktop/NetworkManager/Devices/4", State:0x1e, Interface:"1C:77:F6:E2:B3:4C", HwAddress:"", Managed:true, Vendor:"1C:77:F6:E2:B3:4C", UniqueUuid:"9e05a69b-eedd-fe0a-f90f-c1d6a5005754", UsbDevice:false, ActiveAp:"", MobileNetworkType:"", MobileSignalQuality:0x0}
Jul 15 08:20:44 ideapad daemon/network[1122]: manager_device.go:242: add device &network.device{nmDev:(*networkmanager.Device)(0xc8202e21e0), nmDevWireless:(*networkmanager.DeviceWireless)(nil), mmDevModem:(*modemmanager1.Modem)(nil), nmDevType:0x5, id:"1C:77:F6:E2:B3:4C", udi:"/org/bluez/hci0/dev_1C_77_F6_E2_B3_4C", Path:"/org/freedesktop/NetworkManager/Devices/4", State:0x1e, Interface:"1C:77:F6:E2:B3:4C", HwAddress:"", Managed:true, Vendor:"1C:77:F6:E2:B3:4C", UniqueUuid:"9e05a69b-eedd-fe0a-f90f-c1d6a5005754", UsbDevice:false, ActiveAp:"", MobileNetworkType:"", MobileSignalQuality:0x0}
Jul 15 08:20:45 ideapad com.deepin.daemon.Audio[986]: <warning> window_utils.go:70: Get window pid failed: GetProperty: Error retrieving property '_NET_WM_PID' on window 0: BadWindow {NiceName: Window, Sequence: 8, BadValue: 0, MinorOpcode: 0, MajorOpcode: 20}
Jul 15 08:20:45 ideapad daemon/screenedge[1122]: window_utils.go:70: Get window pid failed: GetProperty: Error retrieving property '_NET_WM_PID' on window 0: BadWindow {NiceName: Window, Sequence: 8, BadValue: 0, MinorOpcode: 0, MajorOpcode: 20}
Jul 15 08:20:45 ideapad com.deepin.daemon.Audio[986]: <warning> window_utils.go:59: Get window name failed: GetProperty: Error retrieving property '_NET_WM_NAME' on window 0: BadWindow {NiceName: Window, Sequence: 11, BadValue: 0, MinorOpcode: 0, MajorOpcode: 20}
Jul 15 08:20:45 ideapad daemon/screenedge[1122]: window_utils.go:59: Get window name failed: GetProperty: Error retrieving property '_NET_WM_NAME' on window 0: BadWindow {NiceName: Window, Sequence: 11, BadValue: 0, MinorOpcode: 0, MajorOpcode: 20}
Jul 15 08:20:53 ideapad daemon/dock[1073]: runtime_apps.go:66: NewRuntimeApp for deepin-terminal
Jul 15 08:20:53 ideapad daemon/dock[1073]: runtime_apps.go:122: deepin-terminal Item docked? false
Jul 15 08:21:02 ideapad com.deepin.daemon.Audio[986]: <info> manager_proxy.go:80: GetProxyMethod none
Jul 15 08:21:02 ideapad daemon/network[1122]: manager_proxy.go:80: GetProxyMethod none
Jul 15 08:21:43 ideapad kernel: usb 2-1: USB disconnect, device number 5
Jul 15 08:21:43 ideapad kernel: option1 ttyUSB0: GSM modem (1-port) converter now disconnected from ttyUSB0
Jul 15 08:21:43 ideapad kernel: option 2-1:1.0: device disconnected
Jul 15 08:21:43 ideapad kernel: option1 ttyUSB1: GSM modem (1-port) converter now disconnected from ttyUSB1
Jul 15 08:21:43 ideapad kernel: option 2-1:1.1: device disconnected
Jul 15 08:21:43 ideapad ModemManager[665]: <info>  (tty/ttyUSB0): released by modem /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1
Jul 15 08:21:43 ideapad ModemManager[665]: <info>  (tty/ttyUSB1): released by modem /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1
Jul 15 08:21:43 ideapad NetworkManager[619]: <info>  (ttyUSB1): device state change: disconnected -> unmanaged (reason 'removed') [30 10 36]
Jul 15 08:21:43 ideapad com.deepin.daemon.Audio[986]: <info> state_handler.go:205: device disconnected, type modem, 30 => 10, reason[36] The device was removed.
Jul 15 08:21:43 ideapad com.deepin.daemon.Audio[986]: <info> manager_device.go:177: device state changed, 30 => 10, reason[36] The device was removed.
Jul 15 08:21:43 ideapad com.deepin.daemon.Audio[986]: <info> utils_notify.go:71: notify notification-network-mobile-3g-disconnected Disconnected The device was removed.
Jul 15 08:21:43 ideapad com.deepin.daemon.Audio[986]: <info> manager_device.go:261: remove device &network.device{nmDev:(*networkmanager.Device)(0xc820348b40), nmDevWireless:(*networkmanager.DeviceWireless)(nil), mmDevModem:(*modemmanager1.Modem)(0xc8201ecc60), nmDevType:0x8, id:"86d0b67e319a669549fcc59fcb296fb903c5b8a4", udi:"/org/freedesktop/ModemManager1/Modem/0", Path:"/org/freedesktop/NetworkManager/Devices/3", State:0x1e, Interface:"ttyUSB1", HwAddress:"", Managed:true, Vendor:"Huawei Technologies E220 HSDPA Modem / E230/E270/E870 HSDPA/HSUPA Modem", UniqueUuid:"9c2c39bd-5248-fd0a-a18d-d88dbb85b241", UsbDevice:true, ActiveAp:"", MobileNetworkType:"3G", MobileSignalQuality:0x20}
Jul 15 08:21:43 ideapad daemon/network[1122]: state_handler.go:205: device disconnected, type modem, 30 => 10, reason[36] The device was removed.
Jul 15 08:21:43 ideapad daemon/network[1122]: manager_device.go:177: device state changed, 30 => 10, reason[36] The device was removed.
Jul 15 08:21:43 ideapad daemon/network[1122]: utils_notify.go:71: notify notification-network-mobile-3g-disconnected Disconnected The device was removed.
Jul 15 08:21:43 ideapad daemon/network[1122]: manager_device.go:261: remove device &network.device{nmDev:(*networkmanager.Device)(0xc820348b40), nmDevWireless:(*networkmanager.DeviceWireless)(nil), mmDevModem:(*modemmanager1.Modem)(0xc8201ecc60), nmDevType:0x8, id:"86d0b67e319a669549fcc59fcb296fb903c5b8a4", udi:"/org/freedesktop/ModemManager1/Modem/0", Path:"/org/freedesktop/NetworkManager/Devices/3", State:0x1e, Interface:"ttyUSB1", HwAddress:"", Managed:true, Vendor:"Huawei Technologies E220 HSDPA Modem / E230/E270/E870 HSDPA/HSUPA Modem", UniqueUuid:"9c2c39bd-5248-fd0a-a18d-d88dbb85b241", UsbDevice:true, ActiveAp:"", MobileNetworkType:"3G", MobileSignalQuality:0x20}
Jul 15 08:21:43 ideapad org.freedesktop.Notifications[986]: QPropertyAnimation: you're trying to animate a non-existing property opacity of your QObject
Jul 15 08:21:43 ideapad org.freedesktop.Notifications[986]: Notify "Network" "notification-network-mobile-3g-disconnected" "Disconnected" "The device was removed." () QMap() 0
Jul 15 08:21:43 ideapad org.freedesktop.Notifications[986]: consumeEntities, entity length:  1
Jul 15 08:21:43 ideapad org.freedesktop.Notifications[986]: updateContent
Jul 15 08:21:43 ideapad org.freedesktop.Notifications[986]: (deepin-notifications:1481): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
Jul 15 08:21:43 ideapad org.freedesktop.Notifications[986]: (deepin-notifications:1481): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
Jul 15 08:21:48 ideapad org.freedesktop.Notifications[986]: bubble is about to quit
Jul 15 08:21:48 ideapad org.freedesktop.Notifications[986]: consumeEntities, entity length:  0
Jul 15 08:21:49 ideapad org.freedesktop.Notifications[986]: bubbleExpired
Jul 15 08:21:49 ideapad org.freedesktop.Notifications[986]: consumeEntities, entity length:  0
Jul 15 08:21:53 ideapad kernel: usb 2-1: new full-speed USB device number 6 using xhci_hcd
Jul 15 08:21:53 ideapad kernel: usb 2-1: New USB device found, idVendor=12d1, idProduct=1003
Jul 15 08:21:53 ideapad kernel: usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Jul 15 08:21:53 ideapad kernel: usb 2-1: Product: HUAWEI Mobile
Jul 15 08:21:53 ideapad kernel: usb 2-1: Manufacturer: HUAWEI Technologies
Jul 15 08:21:53 ideapad kernel: usb-storage 2-1:1.0: USB Mass Storage device detected
Jul 15 08:21:53 ideapad kernel: option 2-1:1.0: GSM modem (1-port) converter detected
Jul 15 08:21:53 ideapad kernel: usb 2-1: GSM modem (1-port) converter now attached to ttyUSB0
Jul 15 08:21:53 ideapad kernel: usb-storage 2-1:1.1: USB Mass Storage device detected
Jul 15 08:21:53 ideapad kernel: option 2-1:1.1: GSM modem (1-port) converter detected
Jul 15 08:21:53 ideapad kernel: usb 2-1: GSM modem (1-port) converter now attached to ttyUSB1
Jul 15 08:21:53 ideapad kernel: usb-storage 2-1:1.2: USB Mass Storage device detected
Jul 15 08:21:53 ideapad kernel: scsi host7: usb-storage 2-1:1.2
Jul 15 08:21:53 ideapad systemd-udevd[1510]: failed to execute '/lib/udev/mtp-probe' 'mtp-probe /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1 2 6': No such file or directory
Jul 15 08:21:53 ideapad ModemManager[665]: <warn>  (ttyUSB1): port attributes not fully set
Jul 15 08:21:54 ideapad kernel: scsi 7:0:0:0: CD-ROM            HUAWEI   Mass Storage     2.31 PQ: 0 ANSI: 2
Jul 15 08:21:54 ideapad kernel: sr 7:0:0:0: [sr1] scsi-1 drive
Jul 15 08:21:54 ideapad kernel: sr 7:0:0:0: Attached scsi CD-ROM sr1
Jul 15 08:21:54 ideapad kernel: sr 7:0:0:0: Attached scsi generic sg2 type 5
Jul 15 08:21:54 ideapad ModemManager[665]: <warn>  (ttyUSB0): port attributes not fully set
Jul 15 08:21:54 ideapad kernel: xhci_hcd 0000:00:14.0: WARN Event TRB for slot 5 ep 6 with no TDs queued?
Jul 15 08:21:54 ideapad kernel: xhci_hcd 0000:00:14.0: WARN Event TRB for slot 5 ep 6 with no TDs queued?
Jul 15 08:21:56 ideapad ModemManager[665]: <warn>  (ttyUSB1): port attributes not fully set
Jul 15 08:21:58 ideapad kernel: xhci_hcd 0000:00:14.0: WARN Event TRB for slot 5 ep 6 with no TDs queued?
Jul 15 08:22:00 ideapad ModemManager[665]: <info>  Creating modem with plugin 'Huawei' and '2' ports
Jul 15 08:22:00 ideapad ModemManager[665]: <warn>  (ttyUSB1): port attributes not fully set
Jul 15 08:22:00 ideapad ModemManager[665]: <info>  Modem for device at '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-1' successfully created
Jul 15 08:22:00 ideapad ModemManager[665]: Error while checking ^SYSCFGEX format: Unknown error
Jul 15 08:22:08 ideapad ModemManager[665]: <warn>  couldn't load Operator identifier: 'SIM failed to handle CRSM request (sw1 103 sw2 0)'
Jul 15 08:22:10 ideapad ModemManager[665]: <warn>  couldn't load list of Own Numbers: 'SIM busy'
Jul 15 08:22:13 ideapad ModemManager[665]: <info>  Modem: state changed (unknown -> disabled)
Jul 15 08:22:13 ideapad NetworkManager[619]: <info>  (ttyUSB1): modem state changed, 'disabled' --> 'enabling' (reason: user preference)
Jul 15 08:22:13 ideapad NetworkManager[619]: <info>  (ttyUSB1): new Broadband device (carrier: UNKNOWN, driver: 'option1', ifindex: 0)
Jul 15 08:22:13 ideapad NetworkManager[619]: <info>  (ttyUSB1): device state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
Jul 15 08:22:13 ideapad NetworkManager[619]: <info>  (ttyUSB1): modem state 'enabling'
Jul 15 08:22:13 ideapad NetworkManager[619]: <info>  (ttyUSB1): device state change: unavailable -> disconnected (reason 'none') [20 30 0]
Jul 15 08:22:13 ideapad ModemManager[665]: <info>  Modem /org/freedesktop/ModemManager1/Modem/1: state changed (disabled -> enabling)
Jul 15 08:22:13 ideapad ModemManager[665]: <warn>  (ttyUSB1): port attributes not fully set
Jul 15 08:22:13 ideapad com.deepin.daemon.Audio[986]: <info> manager_device.go:242: add device &network.device{nmDev:(*networkmanager.Device)(0xc8200c7b30), nmDevWireless:(*networkmanager.DeviceWireless)(nil), mmDevModem:(*modemmanager1.Modem)(0xc8202406c0), nmDevType:0x8, id:"86d0b67e319a669549fcc59fcb296fb903c5b8a4", udi:"/org/freedesktop/ModemManager1/Modem/1", Path:"/org/freedesktop/NetworkManager/Devices/5", State:0x1e, Interface:"ttyUSB1", HwAddress:"", Managed:true, Vendor:"Huawei Technologies E220 HSDPA Modem / E230/E270/E870 HSDPA/HSUPA Modem", UniqueUuid:"9c2c39bd-5248-fd0a-a18d-d88dbb85b241", UsbDevice:true, ActiveAp:"", MobileNetworkType:"Unknown", MobileSignalQuality:0x0}
Jul 15 08:22:13 ideapad daemon/network[1122]: manager_device.go:242: add device &network.device{nmDev:(*networkmanager.Device)(0xc8200c7b30), nmDevWireless:(*networkmanager.DeviceWireless)(nil), mmDevModem:(*modemmanager1.Modem)(0xc8202406c0), nmDevType:0x8, id:"86d0b67e319a669549fcc59fcb296fb903c5b8a4", udi:"/org/freedesktop/ModemManager1/Modem/1", Path:"/org/freedesktop/NetworkManager/Devices/5", State:0x1e, Interface:"ttyUSB1", HwAddress:"", Managed:true, Vendor:"Huawei Technologies E220 HSDPA Modem / E230/E270/E870 HSDPA/HSUPA Modem", UniqueUuid:"9c2c39bd-5248-fd0a-a18d-d88dbb85b241", UsbDevice:true, ActiveAp:"", MobileNetworkType:"Unknown", MobileSignalQuality:0x0}
Jul 15 08:22:13 ideapad ModemManager[665]: <info>  Modem /org/freedesktop/ModemManager1/Modem/1: 3GPP Registration state changed (unknown -> idle)
Jul 15 08:22:13 ideapad ModemManager[665]: <info>  Modem /org/freedesktop/ModemManager1/Modem/1: 3GPP Registration state changed (idle -> registering)
Jul 15 08:22:14 ideapad ModemManager[665]: <info>  Modem /org/freedesktop/ModemManager1/Modem/1: 3GPP Registration state changed (registering -> home)
Jul 15 08:22:14 ideapad ModemManager[665]: <info>  Modem /org/freedesktop/ModemManager1/Modem/1: state changed (enabling -> registered)
Jul 15 08:22:14 ideapad NetworkManager[619]: <info>  (ttyUSB1): modem state changed, 'enabling' --> 'registered' (reason: user-requested)
Jul 15 08:23:18 ideapad kernel: usb 2-1: USB disconnect, device number 6
Jul 15 08:23:18 ideapad kernel: option1 ttyUSB0: GSM modem (1-port) converter now disconnected from ttyUSB0
Jul 15 08:23:18 ideapad kernel: option 2-1:1.0: device disconnected
Jul 15 08:23:18 ideapad kernel: option1 ttyUSB1: GSM modem (1-port) converter now disconnected from ttyUSB1
Jul 15 08:23:18 ideapad kernel: option 2-1:1.1: device disconnected
Jul 15 08:23:18 ideapad ModemManager[665]: <info>  (tty/ttyUSB1): released by modem /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1
Jul 15 08:23:18 ideapad ModemManager[665]: <info>  (tty/ttyUSB0): released by modem /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1
Jul 15 08:23:18 ideapad NetworkManager[619]: <info>  (ttyUSB1): device state change: disconnected -> unmanaged (reason 'removed') [30 10 36]
Jul 15 08:23:18 ideapad com.deepin.daemon.Audio[986]: <info> manager_device.go:177: device state changed, 30 => 10, reason[36] The device was removed.
Jul 15 08:23:18 ideapad com.deepin.daemon.Audio[986]: <info> state_handler.go:205: device disconnected, type modem, 30 => 10, reason[36] The device was removed.
Jul 15 08:23:18 ideapad daemon/network[1122]: manager_device.go:177: device state changed, 30 => 10, reason[36] The device was removed.
Jul 15 08:23:18 ideapad daemon/network[1122]: state_handler.go:205: device disconnected, type modem, 30 => 10, reason[36] The device was removed.
Jul 15 08:23:18 ideapad daemon/network[1122]: utils_notify.go:71: notify notification-network-mobile-3g-disconnected Disconnected The device was removed.
Jul 15 08:23:18 ideapad com.deepin.daemon.Audio[986]: <info> utils_notify.go:71: notify notification-network-mobile-3g-disconnected Disconnected The device was removed.
Jul 15 08:23:18 ideapad com.deepin.daemon.Audio[986]: <info> manager_device.go:261: remove device &network.device{nmDev:(*networkmanager.Device)(0xc8200c7b30), nmDevWireless:(*networkmanager.DeviceWireless)(nil), mmDevModem:(*modemmanager1.Modem)(0xc8202406c0), nmDevType:0x8, id:"86d0b67e319a669549fcc59fcb296fb903c5b8a4", udi:"/org/freedesktop/ModemManager1/Modem/1", Path:"/org/freedesktop/NetworkManager/Devices/5", State:0x1e, Interface:"ttyUSB1", HwAddress:"", Managed:true, Vendor:"Huawei Technologies E220 HSDPA Modem / E230/E270/E870 HSDPA/HSUPA Modem", UniqueUuid:"9c2c39bd-5248-fd0a-a18d-d88dbb85b241", UsbDevice:true, ActiveAp:"", MobileNetworkType:"3G", MobileSignalQuality:0x23}
Jul 15 08:23:18 ideapad daemon/network[1122]: manager_device.go:261: remove device &network.device{nmDev:(*networkmanager.Device)(0xc8200c7b30), nmDevWireless:(*networkmanager.DeviceWireless)(nil), mmDevModem:(*modemmanager1.Modem)(0xc8202406c0), nmDevType:0x8, id:"86d0b67e319a669549fcc59fcb296fb903c5b8a4", udi:"/org/freedesktop/ModemManager1/Modem/1", Path:"/org/freedesktop/NetworkManager/Devices/5", State:0x1e, Interface:"ttyUSB1", HwAddress:"", Managed:true, Vendor:"Huawei Technologies E220 HSDPA Modem / E230/E270/E870 HSDPA/HSUPA Modem", UniqueUuid:"9c2c39bd-5248-fd0a-a18d-d88dbb85b241", UsbDevice:true, ActiveAp:"", MobileNetworkType:"3G", MobileSignalQuality:0x23}
Jul 15 08:23:18 ideapad org.freedesktop.Notifications[986]: Notify "Network" "notification-network-mobile-3g-disconnected" "Disconnected" "The device was removed." () QMap() 0
Jul 15 08:23:18 ideapad org.freedesktop.Notifications[986]: consumeEntities, entity length:  1
Jul 15 08:23:18 ideapad org.freedesktop.Notifications[986]: updateContent
Jul 15 08:23:22 ideapad org.freedesktop.Notifications[986]: bubble is about to quit
Jul 15 08:23:22 ideapad org.freedesktop.Notifications[986]: consumeEntities, entity length:  0
Jul 15 08:23:23 ideapad org.freedesktop.Notifications[986]: bubbleExpired
Jul 15 08:23:23 ideapad org.freedesktop.Notifications[986]: consumeEntities, entity length:  0
Jul 15 08:23:28 ideapad kernel: usb 2-1: new full-speed USB device number 7 using xhci_hcd
Jul 15 08:23:28 ideapad kernel: usb 2-1: New USB device found, idVendor=12d1, idProduct=1003
Jul 15 08:23:28 ideapad kernel: usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Jul 15 08:23:28 ideapad kernel: usb 2-1: Product: HUAWEI Mobile
Jul 15 08:23:28 ideapad kernel: usb 2-1: Manufacturer: HUAWEI Technologies
Jul 15 08:23:28 ideapad kernel: usb-storage 2-1:1.0: USB Mass Storage device detected
Jul 15 08:23:28 ideapad kernel: option 2-1:1.0: GSM modem (1-port) converter detected
Jul 15 08:23:28 ideapad kernel: usb 2-1: GSM modem (1-port) converter now attached to ttyUSB0
Jul 15 08:23:28 ideapad kernel: usb-storage 2-1:1.1: USB Mass Storage device detected
Jul 15 08:23:28 ideapad kernel: option 2-1:1.1: GSM modem (1-port) converter detected
Jul 15 08:23:28 ideapad kernel: usb 2-1: GSM modem (1-port) converter now attached to ttyUSB1
Jul 15 08:23:28 ideapad kernel: usb-storage 2-1:1.2: USB Mass Storage device detected
Jul 15 08:23:28 ideapad kernel: scsi host10: usb-storage 2-1:1.2
Jul 15 08:23:28 ideapad systemd-udevd[1585]: failed to execute '/lib/udev/mtp-probe' 'mtp-probe /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1 2 7': No such file or directory
Jul 15 08:23:28 ideapad ModemManager[665]: <warn>  (ttyUSB1): port attributes not fully set
Jul 15 08:23:29 ideapad kernel: scsi 10:0:0:0: CD-ROM            HUAWEI   Mass Storage     2.31 PQ: 0 ANSI: 2
Jul 15 08:23:29 ideapad kernel: sr 10:0:0:0: [sr1] scsi-1 drive
Jul 15 08:23:29 ideapad kernel: sr 10:0:0:0: Attached scsi CD-ROM sr1
Jul 15 08:23:29 ideapad kernel: sr 10:0:0:0: Attached scsi generic sg2 type 5
Jul 15 08:23:29 ideapad ModemManager[665]: <warn>  (ttyUSB0): port attributes not fully set
Jul 15 08:23:29 ideapad kernel: xhci_hcd 0000:00:14.0: WARN Event TRB for slot 6 ep 6 with no TDs queued?
Jul 15 08:23:31 ideapad ModemManager[665]: <warn>  (ttyUSB1): port attributes not fully set
Jul 15 08:23:33 ideapad kernel: xhci_hcd 0000:00:14.0: WARN Event TRB for slot 6 ep 6 with no TDs queued?
Jul 15 08:23:35 ideapad ModemManager[665]: <info>  Creating modem with plugin 'Huawei' and '2' ports
Jul 15 08:23:35 ideapad ModemManager[665]: <warn>  (ttyUSB1): port attributes not fully set
Jul 15 08:23:35 ideapad ModemManager[665]: <info>  Modem for device at '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-1' successfully created
Jul 15 08:23:35 ideapad ModemManager[665]: Error while checking ^SYSCFGEX format: Unknown error
Jul 15 08:23:43 ideapad ModemManager[665]: <warn>  couldn't load Operator identifier: 'SIM failed to handle CRSM request (sw1 103 sw2 0)'
Jul 15 08:23:45 ideapad ModemManager[665]: <warn>  couldn't load list of Own Numbers: 'SIM busy'
Jul 15 08:23:48 ideapad ModemManager[665]: <info>  Modem: state changed (unknown -> disabled)
Jul 15 08:23:48 ideapad NetworkManager[619]: <info>  (ttyUSB1): modem state changed, 'disabled' --> 'enabling' (reason: user preference)
Jul 15 08:23:48 ideapad NetworkManager[619]: <info>  (ttyUSB1): new Broadband device (carrier: UNKNOWN, driver: 'option1', ifindex: 0)
Jul 15 08:23:48 ideapad NetworkManager[619]: <info>  (ttyUSB1): device state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
Jul 15 08:23:48 ideapad NetworkManager[619]: <info>  (ttyUSB1): modem state 'enabling'
Jul 15 08:23:48 ideapad NetworkManager[619]: <info>  (ttyUSB1): device state change: unavailable -> disconnected (reason 'none') [20 30 0]
Jul 15 08:23:48 ideapad ModemManager[665]: <info>  Modem /org/freedesktop/ModemManager1/Modem/2: state changed (disabled -> enabling)
Jul 15 08:23:48 ideapad ModemManager[665]: <warn>  (ttyUSB1): port attributes not fully set
Jul 15 08:23:48 ideapad com.deepin.daemon.Audio[986]: <info> manager_device.go:242: add device &network.device{nmDev:(*networkmanager.Device)(0xc8203a7770), nmDevWireless:(*networkmanager.DeviceWireless)(nil), mmDevModem:(*modemmanager1.Modem)(0xc8200885a0), nmDevType:0x8, id:"86d0b67e319a669549fcc59fcb296fb903c5b8a4", udi:"/org/freedesktop/ModemManager1/Modem/2", Path:"/org/freedesktop/NetworkManager/Devices/6", State:0x1e, Interface:"ttyUSB1", HwAddress:"", Managed:true, Vendor:"Huawei Technologies E220 HSDPA Modem / E230/E270/E870 HSDPA/HSUPA Modem", UniqueUuid:"9c2c39bd-5248-fd0a-a18d-d88dbb85b241", UsbDevice:true, ActiveAp:"", MobileNetworkType:"Unknown", MobileSignalQuality:0x0}
Jul 15 08:23:48 ideapad daemon/network[1122]: manager_device.go:242: add device &network.device{nmDev:(*networkmanager.Device)(0xc8203a7770), nmDevWireless:(*networkmanager.DeviceWireless)(nil), mmDevModem:(*modemmanager1.Modem)(0xc8200885a0), nmDevType:0x8, id:"86d0b67e319a669549fcc59fcb296fb903c5b8a4", udi:"/org/freedesktop/ModemManager1/Modem/2", Path:"/org/freedesktop/NetworkManager/Devices/6", State:0x1e, Interface:"ttyUSB1", HwAddress:"", Managed:true, Vendor:"Huawei Technologies E220 HSDPA Modem / E230/E270/E870 HSDPA/HSUPA Modem", UniqueUuid:"9c2c39bd-5248-fd0a-a18d-d88dbb85b241", UsbDevice:true, ActiveAp:"", MobileNetworkType:"Unknown", MobileSignalQuality:0x0}
Jul 15 08:23:48 ideapad ModemManager[665]: <info>  Modem /org/freedesktop/ModemManager1/Modem/2: 3GPP Registration state changed (unknown -> idle)
Jul 15 08:23:48 ideapad ModemManager[665]: <info>  Modem /org/freedesktop/ModemManager1/Modem/2: 3GPP Registration state changed (idle -> registering)
Jul 15 08:23:49 ideapad ModemManager[665]: <info>  Modem /org/freedesktop/ModemManager1/Modem/2: 3GPP Registration state changed (registering -> home)
Jul 15 08:23:49 ideapad ModemManager[665]: <info>  Modem /org/freedesktop/ModemManager1/Modem/2: state changed (enabling -> registered)
Jul 15 08:23:49 ideapad NetworkManager[619]: <info>  (ttyUSB1): modem state changed, 'enabling' --> 'registered' (reason: user-requested)
^C
forte@ideapad:~$ 
forte@ideapad:~$ lsusb
Bus 001 Device 002: ID 8087:8001 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 004: ID 0bda:b728 Realtek Semiconductor Corp. 
Bus 002 Device 003: ID 05e3:0510 Genesys Logic, Inc. 
Bus 002 Device 002: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 002 Device 019: ID 12d1:1003 Huawei Technologies Co., Ltd. E220 HSDPA Modem / E230/E270/E870 HSDPA/HSUPA Modem
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
forte@ideapad:~$ rmmcli -M
Could not find the database of available applications, run update-command-not-found as root to fix this
rmmcli: command not found
forte@ideapad:~$ sudo update-command-not-found
I: Writing data for packages.deepin.com_deepin_dists_unstable_contrib_Contents-amd64.bz2 ... . done
I: Writing data for packages.deepin.com_deepin_dists_unstable_main_Contents-amd64.bz2 ... . done
I: Writing data for packages.deepin.com_deepin_dists_unstable_non-free_Contents-i386.bz2 ... . done
I: Writing data for packages.deepin.com_deepin_dists_unstable_main_Contents-i386.bz2 ... . done
I: Writing data for packages.deepin.com_deepin_dists_unstable_contrib_Contents-i386.bz2 ... . done
I: Writing data for packages.deepin.com_deepin_dists_unstable_non-free_Contents-amd64.bz2 ...^[[A . done
forte@ideapad:~$ rmmcli -M
No command 'rmmcli' found, did you mean:
 Command 'mmcli' from package 'modemmanager' (main)
rmmcli: command not found
forte@ideapad:~$ mmcli -M

Found 1 modems:
	/org/freedesktop/ModemManager1/Modem/5 [huawei] E220

Removed modem:
	/org/freedesktop/ModemManager1/Modem/5 [huawei] E220
Added modem:
	/org/freedesktop/ModemManager1/Modem/6 [huawei] E220
Removed modem:
	/org/freedesktop/ModemManager1/Modem/6 [huawei] E220
Added modem:
	/org/freedesktop/ModemManager1/Modem/7 [huawei] E220
^Ccancelling the operation...

forte@ideapad:~$

**Comment by fasheng** [comment]
Do you use a USB-HUB? or maybe the USB contact isn't good, please try it with another computer again.



2016年7月15日 09:37, 09:37，在 Hedi Kasmanto <notifications@github.com> 已写:

**Comment by hedikasmanto** [comment]
Yes, I use Huawei E220 USB dongle. Actually I have tried to connect Deepin laptop using USB-tethering from mobile phone, and it works and proves usb port is working properly. And I also tried to connect Macbook using Huawei E220, and it works too. So I think the problems is not about USB port or my modem device.

**Comment by fasheng** [comment]
I see, how about switching to other DE, does 'mmcli -M' show deviced added/removed repeated, too. If so, it should be a upstream problem, and you could report such issue to modemmanager or usbmodeswitch.



2016年7月15日 18:52, 18:52，在 Hedi Kasmanto <notifications@github.com> 已写:

**Comment by hedikasmanto** [comment]
Before I had installed Deepin 15.2, this laptop use Deepin 14.2 (Ubuntu based) and Linux Mint (Cinnamon DE). The modem can connect without any problem.

**Comment by fasheng** [comment]
Ok, so it even sure caused by  usbmodeswitch/modemmanager related issue, I will seach for  upstream topics later, but could not ensure to solved it in short time...



2016年7月15日 21:36, 21:36，在 Hedi Kasmanto <notifications@github.com> 已写:

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
