### ISSUE TITLE
Please add search box

### ISSUE THREAD

**Issue by bksubhuti** [linuxdeepin/dde-control-center#260]
Please add a search box 
and also activated by CTRL + F
to search for items in the control center also for nested items too.

**Comment by BLumia** [comment]
Hi and it will be there in the next big version release :)

**Comment by bksubhuti** [comment]
Glad to hear this and help out in one way or another.  Best Linux OS out there.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
