### ISSUE TITLE
Switching on window effects crashes UI

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/dde-control-center#264]
On startup window effects are disabled. If I enable them, control-center and the whole window manager crashes and gets restarted - without window effects.

Using Arch Linux (everything up to date) on a Dell XPS13 with all Intel stuff.

It worked until today, where I restarted after a week.

**Comment by BLumia** [comment]
If you are using deepin-wm, please consider switch to dde-kwin by installing the `deepin-kwin` package. Thanks.

**Comment by DasJott** [comment]
That worked out nicely, thank you!
Didn't know that deepin-wm was deprecated.
Can not get rid of that package though by now...

**Comment by DasJott** [comment]
If I want to uninstall deepin-wm, pamac suggests those packages to be removed as well.
Are they all unneeded now? Thx!
![image](https://user-images.githubusercontent.com/6298761/65491170-d3c3a180-deae-11e9-80be-ef73772a7657.png)

**Comment by BLumia** [comment]
not sure about how pamac works but if you use DDE, most of these packages you listed here cannot be removed, deepin-dock is the taskbar of your desktop, deepin-control-center is also the only tools for tweaking DDE, you also need startdde to start the desktop, etc.

You can remove deepin-draw, though..

**Comment by DasJott** [comment]
I thought so.
I would have guessed all those packages depend on deepin-wm. 
Also pacman won't uninstall the package because all the other packages depend on it.
