### ISSUE TITLE
cloud sync tab/card/icon doesn't appear

### ISSUE THREAD

**Issue by annymosse** [linuxdeepin/dde-control-center#265]
hi the cloud sync tab/card/icon doesn't appear for the upgraded versions to 15.11 it seem must remove the old version and reinstall it again i couldn't get a screenshot to attach it as a real issue.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.

**Comment by annymosse** [comment]
@justforlxz actually i have been migrated to ubuntu for the stability and it's performance.
