### ISSUE TITLE
[BUG] Missing animations for Deepin 15.11

### ISSUE THREAD

**Issue by maxjf1** [linuxdeepin/dde-control-center#268]
I have installed the newest version of Deepin, and it is missing some animations/transitions that in previous versions it had.

Here is the launcher animation (and an window opening animation):
![deepin-screen-recorder_Select area_20191008144153](https://user-images.githubusercontent.com/6114888/66419464-8da42d00-e9da-11e9-914d-147b4f1520dd.gif)

What i expected (and experienced in previous versions) (youtube):
[![](http://img.youtube.com/vi/iJpo-RNANPk/0.jpg)](http://www.youtube.com/watch?v=iJpo-RNANPk "Deepin Animations")

Details of my version (i have enabled window effects)
![image](https://user-images.githubusercontent.com/6114888/66419444-88df7900-e9da-11e9-9430-6c636817d0d6.png)

**Comment by maxjf1** [comment]
I also missed the quake terminal transition, but i'm not sure if it existed

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
