### ISSUE TITLE
[archlinux] tap to click button malfunction

### ISSUE THREAD

**Issue by femans** [linuxdeepin/dde-control-center#27]
I use deepin control center on Arch. 
This issue has been here for at least half a year.
When i switch off "tap to click" in mouse settings, this is fine. Tap to click stops.
However, if I reboot, then it is enabled again, although in the settings it is still switched off.

So every time I reboot I have to switch it on again, and switch it off again. (BTW, I can do this by tapping the switch two times =) )

**Comment by fasheng** [comment]
@jouyouyun Any idea?

**Comment by jouyouyun** [comment]
Please paste the output of the command 'gsettings get com.deepin.dde.touchpad tap-to-click' after boot, thanks!

**Comment by femans** [comment]
it says 'false'. However tap to click is enabled.

**Comment by femans** [comment]
ping - any progress on this?

**Comment by fasheng** [comment]
Try to set the gsetting manually and check if it changed after reboot
 ```gsettings set com.deepin.dde.touchpad tap-to-click true```

**Comment by femans** [comment]
Hi, I am sorry but I recently switched to cinnamon, much to my regret. Too many bugs kept entering and too few were getting resolved, and no reply on my bug reports. :(

**Comment by fasheng** [comment]
OK, it doesn't matter. For some reasons the DDE is not stable engough under archlinux, but we will continue to pay attentions to make it better :)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
