### ISSUE TITLE
Not able to switch to custom display modes

### ISSUE THREAD

**Issue by bocekm** [linuxdeepin/dde-control-center#270]
After upgrading from Fedora 30 to Fedora 31, the custom display modes I created in `~/.config/deepin/startdde/display.json` are not showing next to Brightness and Custom settings buttons of the Display section of the control center. The custom modes used to be shown there as separate buttons, one for each custom mode, and I could switch easily between the modes.

For example when I have 3 displays but I want to have only two of them enabled, I need to change the default mode `_dde_display_config_private` in the display.json. Because there's no option to do that in the GUI (Display Custom Settings). When I create a new custom mode manually in the display.json, I can't switch to it from the control center.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
