### ISSUE TITLE
"System Info" module shows UOS icon in community edition

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/dde-control-center#278]
Should a Deepin/DDE logo be used instead?

**Comment by felixonmars** [comment]
![2020-05-02-122633-1b0222](https://user-images.githubusercontent.com/1006477/80855049-2dbfed00-8c70-11ea-9c3c-c6fa82f545bb.png)

**Comment by BLumia** [comment]
@shule1987 already fixed this issue in https://github.com/linuxdeepin/deepin-icon-theme/commit/86d71167595b3e1f88a13f9e627bb8a4cb23c316 if I remember correctly.. cc @xmuli .

**Comment by xmuli** [comment]
Resources have been replaced

![image](https://user-images.githubusercontent.com/33887845/81133904-a632f080-8f85-11ea-86ad-d0f1741f921b.png)
