### ISSUE TITLE
font on power management tab too big

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-control-center#28]
As you can see in the screenshots, the power management tab uses a bigger font than all the other tabs:

![](http://imgur.com/FYIbmiAl.png)

as opposed to for example

![](http://imgur.com/VGTH91sl.png)

**Comment by manateelazycat** [comment]
This issue will fix in next version: deepin 15.4
cc @hualet

**Comment by sbwtw** [comment]
fixed at 15.4
