### ISSUE TITLE
[archlinux] wireless network goes to sleep after laptop resumes from suspend

### ISSUE THREAD

**Issue by femans** [linuxdeepin/dde-control-center#29]
**Since a week or two**, the wireless network manager doesn't wake up after resuming my laptop. 
Once I saw a message in the top right, after I resumed, saying "network manager goes to sleep" or something like that.

I don't know any way to wake up the network manager. However I am able to make it try to connect to a hidden network, which wakes up the network manager. This is of course super tedious.

Now I open and close my laptop sometimes a lot, on conferences for example, and then it is really necessary to be able to use the internet, if I quickly want to look something up. So this is absolutely unpleasant for the whole experience. If a few more of these type of issues arise, I can't use deepin anymore. 

I run on Arch linux, if that makes any difference. I'll be happy to supply any logs or command output.

**Comment by fasheng** [comment]
How about the output of `nmcli dev wifi` after resumed? If is empty, I'm afraid it's the driver issue or NetworkManager issue, and you should find some special error logs in `journalctl -kb`.

**Comment by femans** [comment]
Yeah there are no networks after resume, but they repopulate after I tell
it to connect to a randomly named hidden network.
I have no idea what to look for in the journalctl. Here is the output
```
Aug 20 11:24:02 sputnik kernel: iwlwifi 0000:03:00.0: L1 Enabled - LTR
Enabled
Aug 20 11:24:02 sputnik kernel: iwlwifi 0000:03:00.0: L1 Enabled - LTR
Enabled
Aug 20 11:24:02 sputnik kernel: iwlwifi 0000:03:00.0: L1 Enabled - LTR
Enabled
Aug 20 11:24:02 sputnik kernel: iwlwifi 0000:03:00.0: L1 Enabled - LTR
Enabled
Aug 20 11:24:02 sputnik kernel: IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is
not ready
Aug 20 11:24:02 sputnik kernel: IPv6: ADDRCONF(NETDEV_UP): enp0s25: link is
not ready
Aug 20 11:24:02 sputnik kernel: IPv6: ADDRCONF(NETDEV_UP): enp0s25: link is
not ready
Aug 20 11:24:02 sputnik kernel: IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is
not ready
Aug 20 11:24:04 sputnik kernel: QDBusConnection[11292]: segfault at 15ad580
ip 00000000015ad580 sp 00007f2f16dbba38 error 15
Aug 20 11:24:07 sputnik kernel: ACPI Warning: \_SB.PCI0.PEG.VID._DSM:
Argument #4 type mismatch - Found [Buffer], ACPI requires [Package]
(20160422/nsarguments-95)
Aug 20 11:24:07 sputnik kernel: ACPI Warning: \_SB.PCI0.PEG.VID._DSM:
Argument #4 type mismatch - Found [Buffer], ACPI requires [Package]
(20160422/nsarguments-95)
```
. Any advice on what to do next? Thank you very much!

**Comment by fasheng** [comment]
OK, please upload the syslog tarball which created by the following commads once resumed
```
$ wget https://raw.githubusercontent.com/linuxdeepin/deepin-feedback/master/cli/deepin-feedback-cli.sh
$ chmod +x deepin-feedback-cli.sh
$ sudo ./deepin-feedback-cli.sh
```

**Comment by femans** [comment]
Hi, I am sorry but I switched to cinnamon. Thanks anyway.

**Comment by fasheng** [comment]
OK, that's fine~~
