### ISSUE TITLE
Control Center crash

### ISSUE THREAD

**Issue by vincenzocaselli** [linuxdeepin/dde-control-center#294]
Hi,
with latest update of Deepin DE from Archlinux the Control Center (5.3.0.11-1) doesn't show up.
If from terminal I type:
`dde-control-center `
I get
```
2020-08-20, 00:02:18.521 [Debug  ] [                                                         0] "main window size: 983 * 976" , pid is: 53407
2020-08-20, 00:02:18.559 [Debug  ] [                                                         0] menu is nullptr, create menu!

(process:53407): GLib-GIO-ERROR **: 00:02:18.560: Settings schema 'com.deepin.dde.control-center' does not contain a key named 'crash-signal-enable'
Trace/breakpoint trap (core dumped)
```

**Comment by felixonmars** [comment]
Please try deepin-desktop-schemas-5.8.0.5.20200819-1 and deepin-kwin-5.1.0.20-3. They once again released a deepin-control-center with incompatible schemas and didn’t release the schemas. Also the new dde-kwin is more broken than ever so it took me some time to figure out what happened.

**Comment by vincenzocaselli** [comment]
Thank you @felixonmars , but after some update (now I have 5.3.0.21-1) the problem is gone.
