### ISSUE TITLE
Touchpad switch dead-end ;)

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-control-center#30]
The current situation can lead to an unusable desktop:
When you accidentally or without thinking switch off the Touchpad switch in the 'Mouse and Touchpad' section and you have no working mouse available you have no way of switching your touchpad back on. At least on my hardware the touchpad switch via keyboard will only work after another login.
I think it would be good to either check if another pointer device is present and display a warning in case not, or a warning in any case would also be an option maybe ...

**Comment by oberon2007** [comment]
To provide an alternative keybinding and display it next to the switch would maybe also be a rescue option.

**Comment by fasheng** [comment]
Thanks for the advice, it helps~
@hualet

**Comment by jouyouyun** [comment]
After 15.3, if no mouse exists, will forbbid to disable touchpad.

**Comment by manateelazycat** [comment]
@jouyouyun This issue can close now?

**Comment by jouyouyun** [comment]
Has resolved.
