### ISSUE TITLE
dde-control-center crashing when selecting "Display" or "Power" sections.

### ISSUE THREAD

**Issue by alissonlauffer** [linuxdeepin/dde-control-center#300]
Distro: Arch Linux

When running it directly from terminal with `dde-control-center -s` I get the following errors after clicking these sections:

### Display
```text
GLib-GIO-ERROR **: 04:10:06.611: Settings schema 'com.deepin.dde.control-center' does not contain a key named 'brightness-enable'
```
### Power
```text
GLib-GIO-ERROR **: 04:13:47.631: Settings schema 'com.deepin.dde.control-center' does not contain a key named 'show-hibernate'
```

**Comment by chenweihao1006** [comment]
我这里也有相同问题
Archlinux系统，从桌面邮件打开“显示设置”或者在设置面板里点击“显示”都会闪退

**Comment by RethyI** [comment]
I confirm this. Happened after last update.

**Comment by felixonmars** [comment]
@xmuli There are sync issues in the deepin-desktop-schemas repo.

**Comment by xmuli** [comment]
> @xmuli There are sync issues in the deepin-desktop-schemas repo.

This is already under investigation

**Comment by xmuli** [comment]
@felixonmars @RethyI @chenweihao1006 The wrong character tag in deepin-desktop-schemas caused the synchronization to fail. Now it has been updated normally

**Comment by RethyI** [comment]
@xmuli fresh Arch install, the same behavior. The Display and Power menu kills the control center.

**Comment by mirkobrombin** [comment]
I don't know if there is a connection but in the deepin-desktop-schemas repo, the last two rules in the control-center gsetting file have a different tabulation. Those (brightness and power) are the same entries referenced in the error.

**Comment by bgualda** [comment]
Hello gyus, 

I made an upgrade today and I have the same problem.

1- The first scenario occurs when I select "Display" in Control Center
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 493, resource id: 0, major code: 20 (GetProperty), minor code: 0
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 8 (BadMatch), sequence: 708, resource id: 83886090, major code: 42 (SetInputFocus), minor code: 0
2020-09-19, 17:48:36.587 [Debug  ] [                                                         0] Connected to url: "https://www.archlinux.org/favicon.ico"

(process:7305): GLib-GIO-ERROR **: 17:48:40.959: Settings schema 'com.deepin.dde.control-center' does not contain a key named 'brightness-enable'

2 - The second scenario occurs when I select "Power" in Control Center
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 493, resource id: 0, major code: 20 (GetProperty), minor code: 0
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 8 (BadMatch), sequence: 708, resource id: 83886090, major code: 42 (SetInputFocus), minor code: 0
2020-09-19, 17:48:46.677 [Debug  ] [                                                         0] Connected to url: "https://www.archlinux.org/favicon.ico"

(process:7370): GLib-GIO-ERROR **: 17:48:51.791: Settings schema 'com.deepin.dde.control-center' does not contain a key named 'show-hibernate'
fish: “dde-control-center -s” terminated by signal SIGTRAP (Trace or breakpoint trap)

@xmuli if I understood, you know the problem  and this is about some tags. Do you have any idea when the solution will be available?

**Comment by mirkobrombin** [comment]
The problem seems solved by installing the latest version of deepin-desktop-schemas-git from AUR

**Comment by cacarr-pdxweb** [comment]
Same here. Additionally, Display Settings are also not available from the right-click menu on the desktop.

I shall try the deepin-desktop-schemas-git from AUR solution.

**Comment by cacarr-pdxweb** [comment]
> The problem seems solved by installing the latest version of deepin-desktop-schemas-git from AUR

Confirmed. It has been fixed.

**Comment by TheTBO** [comment]
I have the same issue is it fixed in the repo yet?

**Comment by RethyI** [comment]
> I have the same issue is it fixed in the repo yet?

Yes it is fixed now. Should update.

**Comment by TheTBO** [comment]
Great! update is done and everything works fine now.
Thank you @RethyI
