### ISSUE TITLE
No touchpad settings with the libinput input driver

### ISSUE THREAD

**Issue by deepilla** [linuxdeepin/dde-control-center#32]
I'm running the Deepin Desktop Environment on a laptop with Arch Linux. If I use the [libinput](https://wiki.archlinux.org/index.php/Libinput) input driver instead of [Synaptics](https://wiki.archlinux.org/index.php/Touchpad_Synaptics), the "Mouse and Touchpad" section of the Control Center is completely empty. The touchpad still works but it is not possible to change any settings, e.g. tap to click.

I noticed that the code for [detecting input devices](https://github.com/linuxdeepin/dde-api/blob/master/dxinput/utils/type.c) identifies touchpads by their "Synaptics Off" property. I suspect that when a touchpad uses a non-Synaptics driver such as libinput, Deepin fails to detect it and hides the touchpad configuration settings.

The Arch Linux package manager now recommends libinput over Synaptics (which is in maintenance mode) so it would be great if Deepin could support it. For reference I'm attaching the output of `xinput list-props` for both drivers.

[touchpad-props-libinput.txt](https://github.com/linuxdeepin/dde-control-center/files/501763/touchpad-props-libinput.txt)
[touchpad-props-synaptic.txt](https://github.com/linuxdeepin/dde-control-center/files/501764/touchpad-props-synaptic.txt)

**Comment by snyh** [comment]
I think we can  use the property of "libinput Tapping Enabled" and  "Synaptics Tap Time" to detect whether the device is a touchpad.    @jouyouyun @deepilla

**Comment by jouyouyun** [comment]
In progress, please see: https://cr.deepin.io/16446

**Comment by snyh** [comment]
https://github.com/linuxdeepin/default-settings/blob/master/etc/X11/xorg.conf.d/50-synaptics.conf  

This file should be update to add libinput support too. 
ps:  it should be put under /usr/share/x11/xorg.conf.d/   and  choose a better name.

**Comment by deepilla** [comment]
Any news on this? Is there a plan to release the fix?

**Comment by jouyouyun** [comment]
It is planned to be updated in mid-November, but you can compile dde-api and dde-daemon from master branch yourself.
