### ISSUE TITLE
个性化->通用->窗口圆角［bug］

### ISSUE THREAD

**Issue by patiencewu** [linuxdeepin/dde-control-center#333]
修改窗口圆角后, 切换到其他的设置. 再回来, 会发现圆角的配置修改生效了, 但是显示的却不对

**Comment by xmuli** [comment]
详细说下？

**Comment by xmuli** [comment]
是当默认为最小时候，切出去，但是 dock 没有起作用的话，这个已经修复了，但还没有被集成进去。其你说的生效了，但是显示错误没有遇到。前几天才看了相关代码的

**Comment by patiencewu** [comment]
应该就是这个，其实是生效了，只是界面没有按照实际显示(既然已经修复，就可以了)发自我的华为手机-------- 原始邮件 --------发件人： 偕臧 <notifications@github.com>日期： 2020年12月24日周四 10:18收件人： linuxdeepin/dde-control-center <dde-control-center@noreply.github.com>抄送： patiencewu <patiencewu@126.com>, Author <author@noreply.github.com>主    题： Re: [linuxdeepin/dde-control-center] 个性化->通用->窗口圆角［bug］ (#333)

是当默认为最小时候，切出去，但是 dock 没有起作用的话，这个已经修复了，但还没有被集成进去。其你说的生效了，但是显示错误没有遇到。前几天才看了相关代码的
