### ISSUE TITLE
Unable to delete Pictures Directory  in $HOME

### ISSUE THREAD

**Issue by Nhoya** [linuxdeepin/dde-control-center#34]
Hey there, actually i'm trying to delete the Pictures directory in my home but after each reboot it is recreated by something, i actually disabled the xdg-user-dirs config so i can delete Directories like Downloads and Documents but still can't remove the Pictures dir , any suggestions?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
