### ISSUE TITLE
Add datetime Brasília/São Paulo

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/dde-control-center#35]
Brazil have daylight saving time (DST), not in all country, but in the most part.

Deepin don't have this option, UTC-3:00 DST, in another desktops with Brasília/São Paulo cities.

**Comment by talesam** [comment]
Please include Brazil to setting the date until today has no choice: /

**Comment by manateelazycat** [comment]
@hualet @jouyouyun We need fixed those problem in new control-center of Deepin 15.4

@bigbruno @talesam Thanks for report! ;)

**Comment by hualet** [comment]
@bigbruno @talesam We're working on it, you can choose any standard timezones without any trouble in our next big release. Sorry for the trouble.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
