### ISSUE TITLE
Choosing icons for gtk2 and gtk3 applications separately

### ISSUE THREAD

**Issue by ceyhunnabiyev** [linuxdeepin/dde-control-center#37]
When I choose  icons from dde-control-center, both gtk2 and gtk3 applications take this. In order to choose different  icons for gtk2 applications,  overriding gtk2 configuration files (e.g gtk-icon-theme-name ) doesn't work in Deepin DE.     

Please help me  how I choose icons for gtk2 and gtk3 applications separately??
I am using latest  Archlinux, Deepin DE

**Comment by jouyouyun** [comment]
Sorry, we use XSettings set the theme, GTK will give priority to the value of XSettings, so through the configuration file can not change the theme.

**Comment by ceyhunnabiyev** [comment]
I understood. You mean that Xsettings don't let to select icon theme  for gtk2 and gtk3 applications separately. Thank for answer!!
