### ISSUE TITLE
Change mirror from Brazil, USP to UFPR

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/dde-control-center#38]
Brazil have 2 mirrors of Deepin:
USP - http://sft.if.usp.br/deepin/
UFPR - http://linuxdeepin.c3sl.ufpr.br/

In Deepin Control Center mirror changer, only have USP, but UFPR ir very more stable than USP.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
