### ISSUE TITLE
DND mode not working as expected

### ISSUE THREAD

**Issue by imlinuxuser** [linuxdeepin/dde-control-center#404]
whenever i turn on DND mode, all system notifications are blocked but none of the notifications from (web.whatsapp.com) or any sort of web application or notifications from web browsers are blocked which annoys during work hour.
hope that i am asking the solution in right place.
thank you

**Comment by hualet** [comment]
what browser are you using?

**Comment by babyfengfjx** [comment]
- when you rightclicking on the icon and turing on dnd mode,it Will start the time period set by default；
- Canceling time segment settings can be used properly；
- 
![image](https://user-images.githubusercontent.com/24642999/155067161-9fc27d6c-7693-4ea6-91d3-2582b8c2b9a9.png)

**Comment by babyfengfjx** [comment]
If you recognize my reply, you can close the current Issue, welcome follow-up continue feedback~

**Comment by imlinuxuser** [comment]
> If you recognize my reply, you can close the current Issue, welcome follow-up continue feedback~

Ya i recognised. I m closing the issue.
