### ISSUE TITLE
possibility to disable grubbackgrounditem

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/dde-control-center#41]
Would it be possible to deactivate the grubbackgrounditem in the systeminfo widget for Archlinux and others? Afaik it is not functional there. Or am I wrong?

**Comment by sbwtw** [comment]
we will add complier condition to do this, later.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
