### ISSUE TITLE
Import OpenVPN profile

### ISSUE THREAD

**Issue by avently** [linuxdeepin/dde-control-center#43]
Now Deepin control center does not support importing OpenVPN profiles. Gnome control center supports this. 
For example, I have one file: config.ovpn. This file contains all configuration. Deepin can import this file and connect to VPN.

**Comment by k-plan** [comment]
Solution:

`$ sudo nmcli connection import type openvpn file your-own-openvpn-profile-config-file.ovpn`
`Connection 'your-own-openvpn-profile-config-file' (5b04c610-ca37-4f76-bb61-07e9acdc603a) successfully added.`

Now it will be displayed in `Deepin control center ` => `Network` => `VPN` as  `'your-own-openvpn-profile-config-file'` and you can now start this connection.

**Comment by avently** [comment]
@k-plan ok, thank you!

**Comment by emhaye** [comment]
Import success, but i have problem no route to internet after vpn connect.
On Ubuntu, maybe enable this option `Use this connection only for resources on its network`. How about Deepin?

**Comment by yukatadev** [comment]
@emhaye as an alternative to the `Use this connection only for resources on its network` option you can try using this command:
`$ sudo nmcli connection modify <your_connection_name> ipv4.never-default true`

**Comment by jouyouyun** [comment]
See: https://cr.deepin.io/25291

**Comment by emhaye** [comment]
@yukatadev @jouyouyun Thank's

**Comment by bistungki** [comment]
> @emhaye as an alternative to the `Use this connection only for resources on its network` option you can try using this command:
> `$ sudo nmcli connection modify <your_connection_name> ipv4.never-default true`

Thanks,,bro

**Comment by pablojet** [comment]
just rename to .conf works fine

**Comment by arabkhemar** [comment]
When trying to import an ".ovpn" file I get this error:
`Error: Failed to add 'abcd' connection: connection.uuid: property is missing`
Command was:
`sudo nmcli c import type openvpn file /path/to/abcd.ovpn`
nmcli version is `1.14.6`

**Comment by arieltoledo** [comment]
@arabkhemar same issue here, did you find a work around ?

**Comment by kiratheone** [comment]
its maybe issue form new version of control center. @arieltoledo https://bbs.deepin.org/en/post/231389

**Comment by arieltoledo** [comment]
@kiratheone thanks, will take a look.

**Comment by zhoucs624** [comment]
> just rename to .conf works fine

Yes, :+1:
