### ISSUE TITLE
Artifacting Background

### ISSUE THREAD

**Issue by zentorx** [linuxdeepin/dde-control-center#44]
I'm getting a weird artifacting background on the control center (see picture links below).

This happens wheather I'm using the Vesa drivers or the amdgpu one. (I have an RX 480).

This issue however does not happen anywhere else in the Desktop environment, and it does not happen at all inside a VM.

Picture links:

-> http://i.imgur.com/UQaBYJj.jpg 
-> http://i.imgur.com/PvGIbET.jpg

Let me know if you need any further information!

**Comment by sonald** [comment]
Which linux distribution did you use? It seems that your 3D does not work properly. plz execute `ps -ef |grep wm` on a terminal to see which window manager is running.

**Comment by sonald** [comment]
@felixonmars does archlinux use the patched clutter now ?

**Comment by felixonmars** [comment]
@sonald Not yet... It would be great if you can create a fork :)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
