### ISSUE TITLE
weird laggy scrolling when using touchpad

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/dde-control-center#45]
As long as I use my mousewheel  scrolling up and down the control center works fine, but as soon as I use the two-finger scrolling function of my touchpad it's extremely laggy. Everywhere else on the system I don't have any issue with that, only inside the control-center.

**Comment by foliea** [comment]
I have the same issue.

**Comment by oberon2007** [comment]
are all of us using **libinput**? can anyway try switching to **synaptics** to see if that makes a difference?

**Comment by funilrys** [comment]
@oberon2007 what 'weird laggy' mean? I use synaptics and have no problem with touchpad under control-center!

**Comment by funilrys** [comment]
@oberon2007 I use synaptics and it's 'laggy' only when I scroll up

**Comment by funilrys** [comment]
@oberon2007 @foliea Just discovered that you can click and go up or down like we do on smartphone or tablet but with touchpad (very strange I know)


maybe it's the source of the problem ...

**Comment by GNOME-IS-LIFE** [comment]
If on Libinput you have horizontal scrolling enabled, you need to scroll left and right. Not the best solution, but better than the up and down lag scroll

**Comment by navdeepio** [comment]
similar problem but with firefox on ubuntu... the only issue on an otherwise awesome system setup

**Comment by maxjf1** [comment]
This happens when you enable horizontal scrolling. The solution for me so far was to scroll on diagonal.

Demo (trying to srolling down):

![deepin-screen-recorder_Select area_20191024161416](https://user-images.githubusercontent.com/6114888/67517643-63f53200-f679-11e9-9383-322f8121fb6f.gif)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
