### ISSUE TITLE
battery remaining time

### ISSUE THREAD

**Issue by joksik** [linuxdeepin/dde-control-center#46]
it`s possible to show remaining time for battery when we click on the battery icon?? at now i see only battery % but i don`t have any clue how long my laptop can work

**Comment by GNOME-IS-LIFE** [comment]
I second this! Any work done on this? What though, I think this should go in Deepin dock, not control centre

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
