### ISSUE TITLE
Control Panel is Dialing Home AND Over Unsecured

### ISSUE THREAD

**Issue by dantheman213** [linuxdeepin/dde-control-center#47]
I noticed there was an issue with the weather widget when I recently installed the Deepin Desktop DE for my Manjaro Linux installation. I pulled the code down and upon inspection I noticed there are at least 2 times in the code that you "phone home" to 3rd party servers. This WAS NOT made aware at any point while I was installing or using your code.

![image](https://cloud.githubusercontent.com/assets/10934533/22896858/848fd696-f1d6-11e6-8ca1-b4e993b50cfc.png)

Why was this put into place? I (and I'm sure 99.999999%) of your users want this removed. If you want to use a 3rd party weather API you should include multiple options of high quality 3rd party providers and I should be able to choose which API and enter my own API key myself.

In addition to that, I do NOT want my desktop environment dialing home or to other servers sending my information to them. Especially without my permission --AND especially not over HTTP (unsecured).

How is the Deepin team going to rectify this issue?

**Comment by dongfengweixiao** [comment]
cause now developers cannot find FREE & HIGH quality 3rd party providers,and current weather services only provide for test. We believe that developers will use quality weather service providers in the near future.

**Comment by michaldybczak** [comment]
Why can't they use those that are used in other DEs successfully? Currently on Plasma yr.no works well for me.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.

**Comment by dantheman213** [comment]
Good thing you closed this ticket years after being created rather than fix the unsecured dial home code.

**Comment by justforlxz** [comment]
> Good thing you closed this ticket years after being created rather than fix the unsecured dial home code. 

This function is no longer used, and the code can be deleted at any time.
