### ISSUE TITLE
DNS problem

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/dde-control-center#48]
I'm found one big problem, present in 15.3 and 15.4

If change dns for network in deepin control center, just add in bottom of /etc/resolv.conf

Thus not really change DNS, principal DNS in use maintain default received in DHCP, need remove DNS received in DHCP for really work

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
