### ISSUE TITLE
[Archlinux] deepin-control-center 4.0.8-1 broken

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-control-center#49]
```
$ dde-control-center
dde-control-center: symbol lookup error: dde-control-center: undefined symbol: _ZNK9__Display22HasCustomConfigChangedEb
```
@felixonmars

**Comment by felixonmars** [comment]
Not present in Arch AFAICS.

**Comment by oberon2007** [comment]
@sbwtw maybe this is related to my icon issue? I keep thinking that I'm missing a library??

**Comment by oberon2007** [comment]
https://github.com/linuxdeepin/dde-control-center/commit/c1701cf8911693b33893ad8b3893e41c38a437c2#diff-79d49a05048d461454027ce150a7461bR25

**Comment by oberon2007** [comment]
Ah. I see. That commit is only in **4.0.9**, so apparently was the issue in **4.0.8** :wink:

**Comment by oberon2007** [comment]
Solved with the update to **4.0.9**

**Comment by timhere** [comment]
I didn't have this issue previously but I now can't open dde-control-center after the latest update.

`dde-control-center: symbol lookup error: dde-control-center: undefined symbol: _ZN10__Miracast7RemovedERK15QDBusObjectPath`

**Comment by felixonmars** [comment]
It's not the same problem.
