### ISSUE TITLE
Network configuration to ignore hosts

### ISSUE THREAD

**Issue by ricardodesimas** [linuxdeepin/dde-control-center#5]
How can I add some hosts to ignore in the System Proxy configuration?

There aren't any field to add this config in the Network control center.

**Comment by fasheng** [comment]
Well, there is no interface for such work now. If your application detect environment variable like `$no_proxy`, you could create a script in `/etc/profile.d` and paste following content:

    export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"

In fact, the system proxy work not well now for that many application not support the environment variables like `$http_proxy`, `$SOCKS_SERVER`. We plan to re-implement it later.

**Comment by ricardodesimas** [comment]
Ok, I'm using the envirnment variable $no_proxy, but I've to change in every user of the system, and sometimes doesn't work in anyway.

What I and doing is changing in the dconf-editor.

Thank you for the explanation and I'm hoping that you can release a fix for that soon.
