### ISSUE TITLE
[Archlinux] Apps are always on top of control center

### ISSUE THREAD

**Issue by moham96** [linuxdeepin/dde-control-center#50]
control center is showing in the background of any running app, but when hovering the mouse over the left area or clicking the mouse events get sent to the control center in the background.Is this a bug or a configurable setting?
![deepin-screen-recorder_desktop_20170318125902](https://cloud.githubusercontent.com/assets/10559702/24071181/f5c6b8fa-0bdc-11e7-8b23-d829fedd656e.gif)

[pkglist.txt](https://github.com/linuxdeepin/dde-control-center/files/852324/pkglist.txt)

**Comment by GNOME-IS-LIFE** [comment]
doesn't happen with me in deepin, arch, or even manjaro

**Comment by moham96** [comment]
@GNOME-IS-LIFE  i think the bug was resolved shortly after i reported it.

**Comment by sbwtw** [comment]
@sonald look?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
