### ISSUE TITLE
wifi network manager not save password of archlinux

### ISSUE THREAD

**Issue by a-wing** [linuxdeepin/dde-control-center#51]
only one password save
need many wifi password manager

**Comment by jouyouyun** [comment]
Please enter into  `/etc/NetworkManager/system-connections/` directory, then check the file by ssid named whether has your password, thanks!

**Comment by a-wing** [comment]
But swift wifi have problem sometime wifi-password no load 
Hot swift wifi have same password is NULL

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
