### ISSUE TITLE
suggestion hot zone add show workspace

### ISSUE THREAD

**Issue by a-wing** [linuxdeepin/dde-control-center#52]
建议在热区里添加显示工作区

**Comment by aiamuzz** [comment]
i guess dde-control-center is the wrong place ... i have added it to the right one though ...

https://github.com/linuxdeepin/deepin-wm/issues/22

**Comment by jouyouyun** [comment]
@hualet

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
