### ISSUE TITLE
[Archlinux] Can not open dde-control-center v4.0.14

### ISSUE THREAD

**Issue by VeselovAlex** [linuxdeepin/dde-control-center#54]
Same as commented [here](https://github.com/linuxdeepin/dde-control-center/issues/49#issuecomment-290917930):

dde-control-center starts with an error:
```
$ dde-control-center 
dde-control-center: symbol lookup error: dde-control-center: undefined symbol: _ZN10__Miracast7RemovedERK15QDBusObjectPath
```

**Comment by felixonmars** [comment]
Fixed in 4.0.14.20170401-1.

See https://github.com/linuxdeepin/developer-center/issues/226 for more info.
