### ISSUE TITLE
Internet speed issue with wifi

### ISSUE THREAD

**Issue by ceyhunnabiyev** [linuxdeepin/dde-control-center#58]
I have 20 mbps wifi , in speedtest shows 1-5 mbps , please help me, how solve this problem??

I am using latest Manjaro , Deepin stable..

**Comment by jouyouyun** [comment]
The real speed is one-eighth of the bandwidth, so should be 20/8 = 2.5

**Comment by ceyhunnabiyev** [comment]
No, I  said same unit(mbit per sec)  Ok, this was fixed for me for two days.. Sorry for that..
