### ISSUE TITLE
Temperature is in Celsius. 

### ISSUE THREAD

**Issue by SylveonBottle** [linuxdeepin/dde-control-center#61]
American here. We use Fahrenheit. There doesn't seem to be a setting to change the Weather to use Fahrenheit.
![deepinscreenshot20170526033535](https://cloud.githubusercontent.com/assets/17802843/26487272/70064c80-41c4-11e7-8f6f-72e0556bd8c5.png)

**Comment by GNOME-IS-LIFE** [comment]
I second this!

**Comment by GNOME-IS-LIFE** [comment]
Any update?

**Comment by sbwtw** [comment]
Not implement yet. I think is necessary to add a config option for this.

**Comment by kirigayakazushin** [comment]
append TemperatureFormat=yes to ~/.config/deepin/dcc-weather-plugin.conf

**Comment by SylveonBottle** [comment]
Forgot to make an update, what @kirigayakazushin suggested is the correct method to fixing this.

Originally found in the comment sections [here](http://feedback.deepin.org/feedback/detail/7743?language=en_US).

Would be nice to receive a proper setting for this in the GUI, but I'm fin with changing the .conf.

**Comment by oberon-manjaro** [comment]
@haruyukilxz I just tried your suggested config but the problem is, this only works for the current temparature, while it seems to have no effect on the weather preview! :stuck_out_tongue_winking_eye: 

![screenshot_2018-09-30_10-32-31](https://user-images.githubusercontent.com/11800714/46254737-7f086900-c49c-11e8-848e-a91626c767d2.png)

**Comment by jouyouyun** [comment]
@haruyukilxz

**Comment by haruyukilxz** [comment]
@oberon-manjaro thanks, I fixed.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
