### ISSUE TITLE
disable displays

### ISSUE THREAD

**Issue by magynhard** [linuxdeepin/dde-control-center#62]
Unfortunately there is no function to disable connected displays with the display manager.

Especially when using a laptop, connected with two external displays, it is a common way to disable the laptop display. But there is no feature yet to do so.

A feature, allowing to disable/enable connected displays would be great.

UI idea: There may be an (eye) icon inside of each display in the display manager, that can be striken by the user (check box mode).

**Comment by bocekm** [comment]
There is a workaround - to change the ~/.config/deepin/startdde/display.json` manually. Set `"Enabled": false,` for the display you want disabled. Related: https://github.com/linuxdeepin/dde-control-center/issues/270.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
