### ISSUE TITLE
Natural scrolling functionality removed after reboot

### ISSUE THREAD

**Issue by Xafloc** [linuxdeepin/dde-control-center#63]
The natural scrolling functionality loses effect after a reboot, despite the settings remaining "enabled" in the control center.  To get natural scrolling to work again, one must disable, then re-enable the setting.

Steps to reproduce:
  -Enable natural scrolling (test)
  -Reboot
  -Verify setting is still enabled
  -Attempting to scroll will result in standard scrolling until you disable, and re-enable the setting

**Comment by kirigayakazushin** [comment]
We have fixed this issue and will be updated in the new version.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
