### ISSUE TITLE
控制中心没有蓝牙图标

### ISSUE THREAD

**Issue by Kuangcp** [linuxdeepin/dde-control-center#64]
更新到了15.4最新版，蓝牙就不见了，sudo rfkill list 执行后 都是 no
求解决，因为deepin直接用笔记本的音响声音失真，现在蓝牙音响也用不了，那就有点不方便了

**Comment by sbwtw** [comment]
bluetoothctl 能发现和控制你的蓝牙设备吗

**Comment by Kuangcp** [comment]
看不到打开蓝牙的那个设置项～

**Comment by sbwtw** [comment]
终端执行
```
$ bluetootlctl
```
然后在 bluttoothctl 界面执行
```
list devices
```

**Comment by Kuangcp** [comment]
[bluetooth]# nnect to bluetoothd...

运行后只是提示这个，然后等了好久都这样

**Comment by sbwtw** [comment]
bluetooth 没有启动，执行
```
sudo systemctl start bluetooth
```
你是 deepin 的系统还是 arch

**Comment by Kuangcp** [comment]
kcp@myth-kuang:~$ sudo systemctl start bluetooth
kcp@myth-kuang:~$ bluetoothctl
[bluetooth]# nnect to bluetoothd...

没反应。。。。。deepin，我给两个室友新装的系统也没有蓝牙

**Comment by sbwtw** [comment]
可以确定是你的蓝牙服务没有启动，执行
```
sudo systemctl status bluetooth
```
来查看蓝牙的运行状态

**Comment by Kuangcp** [comment]
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
   Active: active (running) since 日 2017-06-11 14:18:04 CST; 1 weeks 5 days ago
     Docs: man:bluetoothd(8)
 Main PID: 2358 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 4915)
   Memory: 1.1M
      CPU: 377ms
   CGroup: /system.slice/bluetooth.service
           └─2358 /usr/lib/bluetooth/bluetoothd

6月 13 14:30:25 myth-kuang bluetoothd[2358]: Endpoint registered: sender=:1.63 path=/MediaEndpoint/A2DPSink
6月 14 10:56:51 myth-kuang bluetoothd[2358]: Endpoint unregistered: sender=:1.63 path=/MediaEndpoint/A2DPSource
6月 14 10:56:51 myth-kuang bluetoothd[2358]: Endpoint unregistered: sender=:1.63 path=/MediaEndpoint/A2DPSink
6月 14 10:57:30 myth-kuang bluetoothd[2358]: Failed to obtain handles for "Service Changed" characteristic
6月 14 10:57:30 myth-kuang bluetoothd[2358]: Sap driver initialization failed.
6月 14 10:57:30 myth-kuang bluetoothd[2358]: sap-server: Operation not permitted (1)
6月 14 10:57:30 myth-kuang bluetoothd[2358]: Endpoint registered: sender=:1.63 path=/MediaEndpoint/A2DPSource
6月 14 10:57:30 myth-kuang bluetoothd[2358]: Endpoint registered: sender=:1.63 path=/MediaEndpoint/A2DPSink
6月 14 15:41:29 myth-kuang bluetoothd[2358]: Endpoint unregistered: sender=:1.63 path=/MediaEndpoint/A2DPSource
6月 14 15:41:29 myth-kuang bluetoothd[2358]: Endpoint unregistered: sender=:1.63 path=/MediaEndpoint/A2DPSink


运行结果是这样的，好像这是说已经开启了吧，但是有错误，对了，现在重启下 控制栏底部只有一个图标了，只有wifi
