### ISSUE TITLE
DISABLE_SYS_UPDATE incomplete

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-control-center#66]
When compiling with `DISABLE_SYS_UPDATE`, the entry for Update in navwidget is still created.
Could you kindly add some more `#ifndef`s in **plugins/navgation/navwidget.cpp**, maybe?
@sbwtw

**Comment by oberon2007** [comment]
This issue is still present. 
![screenshot_2018-01-14_23-05-21](https://user-images.githubusercontent.com/11800714/34921232-b2564482-f97f-11e7-972f-d9bae83c124d.png)
Any hope this will be fixed?
@felixonmars

**Comment by oberon2007** [comment]
Same as https://github.com/linuxdeepin/dde-control-center/issues/59
```
diff -rupN a/plugins/navgation/navwidget.cpp b/plugins/navgation/navwidget.cpp
--- a/plugins/navgation/navwidget.cpp	2017-11-29 04:38:56.000000000 +0100
+++ b/plugins/navgation/navwidget.cpp	2018-01-15 01:20:57.911307016 +0100
@@ -30,7 +30,7 @@
 
 const QStringList MODULES = { "accounts", "display", "defapp", "personalization", "network",
                               "bluetooth", "sound", "datetime", "power", "mouse", "keyboard",
-                              "wacom", "update", "systeminfo" };
+                              "wacom", "systeminfo" };
 
 NavWidget::NavWidget(QWidget *parent)
     : QWidget(parent),
```
Maybe not a super clean solution, but effective.

**Comment by felixonmars** [comment]
Fixed in 4.3.7-2. Upstream CR: https://cr.deepin.io/#/c/30551/

**Comment by sbwtw** [comment]
Oops. Sorry for delay

**Comment by oberon2007** [comment]
Thank you! 😄 👍
