### ISSUE TITLE
Feature request: Advanced settings

### ISSUE THREAD

**Issue by trunapushpa** [linuxdeepin/dde-control-center#68]
I used deepin for a day and couldn't find some advanced settings options like:

1. Enable/disable edge/two-fingered scrolling.
2. Network Manger is missing, can't create a connection. I need Wifi Hotspot on a daily basis, but couldn't find anywhere.

**Comment by steve-todorov** [comment]
Big thumbs up for edge/two-fingered scrolling!!

**Comment by aiamuzz** [comment]
Hotspot is implemented already in Deepin 15.5 Beta
Creating a connection can be achieved by using 'Network -> Wireless -> Connect to hidden networks'

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
