### ISSUE TITLE
Setting for touchpad gestures

### ISSUE THREAD

**Issue by joachimwolff** [linuxdeepin/dde-control-center#69]
Is there somewhere a setting for the gestures which are supported and maybe to turn on / off specific ones? I can not find something like this in the control center.

**Comment by kirigayakazushin** [comment]
sorry,custom touchpad gestures is not supported now.

**Comment by GNOME-IS-LIFE** [comment]
huh what!? @kirigayakazushin you can just go to /usr/share/dde-daemon/gesture.json and configure them manually, or in ~/.config/deepin/dde-daemon/gesture.json

what is stopping you from making a GUI which edits the original file (/usr/share....) and save it per user in (~/.config.....) It seems like it would help a lot!

**Comment by GNOME-IS-LIFE** [comment]
Why'd you close the issue? We have proof that it, infact we CAN fix it! There is a .json file to change the touchpad Gestures through CLI and can be put per user basis, so open the issue! This is fixable! All that's missing is a GUI!

**Comment by GNOME-IS-LIFE** [comment]
Oh wait sorry I reread your initial post and saw you just needed the settings, not a GUI in the settings control centre to do it. Keep this closed, I'll make a new issue for fixing this :D btw a thanks wouldn't hurt

**Comment by sircipolatti** [comment]
Hello Firstly, I would like to congratulate the work of the Deepin OS team. I migrated from Ubuntu and I'm satisfied in many ways.
If this topic is closed, but I would like to let you know that a GUI for setting advanced gestures on the touchpad would be great. I've been looking for this for years in linux and have never found anything professional.
I think it would be a plus for Deepin.
Thank you.

**Comment by vabhinivesh** [comment]
My laptop Lenovo did not detect my touchpad. Please help. am very much satisfied in deepin os

**Comment by willianpraciano** [comment]
If you want to add some custom gestures to your touchpaf, in linux Deepin you can edit the _gesture.json_ file inside the folder  `/usr/share/dde-daemon`.

Mine is like this:

> [
    {
        "Name": "swipe",
        "Direction": "up",
        "Fingers": 3,
        "Action": {
            "Type": "built-in",
            "Action": "ShowAllWindow"
        }
    },
    {
        "Name": "swipe",
        "Direction": "down",
        "Fingers": 3,
        "Action": {
            "Type": "built-in",
            "Action": "Minimize"
        }
    },
    {
        "Name": "swipe",
        "Direction": "left",
        "Fingers": 3,
        "Action": {
            "Type": "built-in",
            "Action": "ReverseSwitchApplication"
        }
    },
    {
        "Name": "swipe",
        "Direction": "right",
        "Fingers": 3,
        "Action": {
            "Type": "built-in",
            "Action": "SwitchApplication"
        }
    },
    {
        "Name": "pinch",
        "Direction": "in",
        "Fingers": 3,
        "Action": {
            "Type": "built-in",
            "Action": "ShowWindow"
        }
    },
    {
        "Name": "pinch",
        "Direction": "out",
        "Fingers": 3,
        "Action": {
            "Type": "built-in",
            "Action": "ShowWindow"
        }
    },
    {
        "Name": "tap",
        "Direction": "none",
        "Fingers": 3,
        "Action": {
            "Type": "commandline",
            "Action": "qdbus --literal com.deepin.dde.Launcher /com/deepin/dde/Launcher com.deepin.dde.Launcher.Toggle"
        }
    },
    {
        "Name": "swipe",
        "Direction": "up",
        "Fingers": 4,
        "Action": {
            "Type": "built-in",
            "Action": "ShowWorkspace"
        }
    },
    {
        "Name": "swipe",
        "Direction": "down",
        "Fingers": 4,
        "Action": {
            "Type": "built-in",
            "Action": "ShowWorkspace"
        }
    },
    {
        "Name": "swipe",
        "Direction": "left",
        "Fingers": 4,
        "Action": {
            "Type": "built-in",
            "Action": "ReverseSwitchWorkspace"
        }
    },
    {
        "Name": "swipe",
        "Direction": "right",
        "Fingers": 4,
        "Action": {
            "Type": "built-in",
            "Action": "SwitchWorkspace"
        }
    },
    {
        "Name": "pinch",
        "Direction": "in",
        "Fingers": 4,
        "Action": {
            "Type": "commandline",
            "Action": "qdbus --literal com.deepin.dde.Launcher /com/deepin/dde/Launcher com.deepin.dde.Launcher.Toggle"
        }
    },
    {
        "Name": "tap",
        "Direction": "none",
        "Fingers": 4,
        "Action": {
            "Type": "commandline",
            "Action": "/usr/lib/deepin-daemon/default-terminal"
        }
    },
    {
        "Name": "swipe",
        "Direction": "up",
        "Fingers": 5,
        "Action": {
            "Type": "built-in",
            "Action": "ShowWorkspace"
        }
    },
    {
        "Name": "swipe",
        "Direction": "down",
        "Fingers": 5,
        "Action": {
            "Type": "built-in",
            "Action": "ShowWorkspace"
        }
    },
    {
        "Name": "swipe",
        "Direction": "left",
        "Fingers": 5,
        "Action": {
            "Type": "built-in",
            "Action": "ReverseSwitchWorkspace"
        }
    },
    {
        "Name": "swipe",
        "Direction": "right",
        "Fingers": 5,
        "Action": {
            "Type": "built-in",
            "Action": "SwitchWorkspace"
        }
    },
    {
        "Name": "pinch",
        "Direction": "in",
        "Fingers": 5,
        "Action": {
            "Type": "commandline",
            "Action": "qdbus --literal com.deepin.dde.Launcher /com/deepin/dde/Launcher com.deepin.dde.Launcher.Toggle"
        }
    },
    {
        "Name": "pinch",
        "Direction": "out",
        "Fingers": 5,
        "Action": {
            "Type": "commandline",
            "Action": "/usr/lib/deepin-daemon/desktop-toggle"
        }
    }
]

**Comment by LucasAlda** [comment]
@willianpraciano i made the same changes to gestures.json, but deepin never applied them

**Comment by willianpraciano** [comment]
> @willianpraciano i made the same changes to gestures.json, but deepin never applied them

You must restart the system or logoff after saving changes.

**Comment by LucasAlda** [comment]
> @LucasAlda you must restart the system or logoff after saving changes.
Of course, i rebooted the system after saving but the gestures still being the same Even though the file has the new ones.
