### ISSUE TITLE
GeoIP *gi may be NULL in NetworkUtil::ip2city(const QString &ip)

### ISSUE THREAD

**Issue by quadpixels** [linuxdeepin/dde-control-center#71]
https://github.com/linuxdeepin/dde-control-center/blob/873e6d750ca86272a1e26aadbd4b3bba685a3a7b/plugins/weather/networkutil.cpp#L79

Hello developers,
I found that the variable `gi` on this line may yield a NULL on my particular setup, which causes the Control Center to disappear after 0.5 ~ 1 second after opening, making it very annoying and impractical to use. Putting a NULL value check `if (gi != NULL)` around lines around 83 and 86 seems to fix this issue for now, and I'll try to come up with more information on why `gi` can become NULL.

I'm compiling the latest version of DDE Control Center, 4.2.5.10, on an Xubuntu 17.04 setup.

Thanks!

**Comment by kirigayakazushin** [comment]
Thanks!  I fix it in https://cr.deepin.io/#/c/27978/

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
