### ISSUE TITLE
Tweak request : Fast Screen Off ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-control-center#75]
I was looking for a way to just make my screen go dark at will ... didn't want to install any ubuntu solutions to achieve the same ... there have been quite a few times when i had to leave my system ON overnight for torrentz / updates ... don't laugh ... i would actually drape the screen with a hanky :) ... to cut the glare of the lock screen while i doze ...

accidentally i came across 'fast screen off' setting in the 'corner settings ... it isn't fit for a corner settings though as even accidentally bumping into the corner would unnecessarily would push the screen dark.

i would painstakingly replace the 'close' corner setting to 'fast screen off' instead of draping a hanky over my screen for a night run and switch back to the 'close' corner setting ... quite the circus there :)

I was wondering ... wouldn't it be better to couple 'fast screen off' with the 'screen lock' action both by way of 'power button -> lock ' or 'windows key+l' ... would serve my purpose ... and it makes sense too ... 

NOTE : if that(fast screen off is coupled with lock-screen) then you'd have to have a timer on the lock screen as well for it to go dark just in case a key gets pressed while the system is locked ... if not the screen will be lit up after the accidental key press forever.

further wouldn't it be ideal to have 'fast screen off' as a system shortcut in keyboard settings ?
just a magical screen off wand ... without the lock screen ?

cheers

**Comment by aiamuzz** [comment]
while this is considered ... could someone give me the command to trigger the 'fast screen off' ?
i could create a custom shortcut key ... an Alt+Esc (quick reflex) or a slower WinKey+s or WinKey+o ... would make a nice system shortcut ... don't you think ?

**Comment by aiamuzz** [comment]
is `xset dpms force suspend` the command that enforces 'fast screen off' hot corner setting by any chance ?

**Comment by aiamuzz** [comment]
ok ... i think i have messed something up ... the 'fast screen off' was supposed to just switch off the monitor, i had used it last night ... and the system was ON with the screen OFF ... even my custom shortcut `xset dpms force suspend` was doing exactly that ...

But now i see something has changed/broken ... i just ran the latest deepin update from control center ... not sure if that is the trigger point ... but now suddenly 'fast screen off' as well as the command `xset dpms force suspend` are actually suspending the whole system/machine ...

hmmmmm ... what broke/changed ???

**Comment by jouyouyun** [comment]
Close screen: `sleep 1; xset dpms force off`

**Comment by aiamuzz** [comment]
Hi,
i am sorry ... `xset dpms force off` ... is putting the whole machine to suspend(i have to use power button to wake it up) ... even 'fast screen off' corner setting is forcing a machine suspend(i have to use power button to wake it up)

**Comment by jouyouyun** [comment]
The  'fast screen off'  equal with `xset dpms force off`, but why suspend when close screen?

**Comment by aiamuzz** [comment]
i don't know it was working fine before the last system updates were pushed through the control-center !!!
Is it a bug ?
something broken after last update ?

the 'fast screen off' was working perfectly well before ... even the `xset dpms force suspend` was working perfectly fine.

let me know if you need any outputs out of my affected system.

**Comment by jouyouyun** [comment]
Please exec `sudo journalctl -f > /tmp/sys.log` then exec `xset dpms force off`, then upload the file `/tmp/sys.log` and `/var/log/Xorg.0.log` after wakeup, thanks!

**Comment by aiamuzz** [comment]
here you go ...

`/tmp/sys.log`  
[sys.log](https://github.com/linuxdeepin/dde-control-center/files/1486820/sys.log)

`/var/log/Xorg.0.log`
[Xorg.0.log](https://github.com/linuxdeepin/dde-control-center/files/1486822/Xorg.0.log)

**Comment by jouyouyun** [comment]
Please paste the outputs for `gsettings list-recursively com.deepin.dde.power`, thanks!

**Comment by jouyouyun** [comment]
@electricface

**Comment by aiamuzz** [comment]
sure ...


```
gsettings list-recursively com.deepin.dde.power

com.deepin.dde.power sleep-lock true
com.deepin.dde.power fullscreen-workaround-enabled true
com.deepin.dde.power percentage-low 20
com.deepin.dde.power time-to-empty-critical 600
com.deepin.dde.power screen-black-lock false
com.deepin.dde.power line-power-screen-black-delay 900
com.deepin.dde.power time-to-empty-action 300
com.deepin.dde.power use-percentage-for-policy true
com.deepin.dde.power percentage-critical 10
com.deepin.dde.power percentage-action 5
com.deepin.dde.power power-button-pressed-exec 'dde-shutdown'
com.deepin.dde.power fullscreen-workaround-app-list ['libflash', 'chrome', 'firefox', 'mplayer', 'operaplugin', 'soffice', 'wpp', 'evince', 'vlc', 'totem']
com.deepin.dde.power line-power-sleep-delay 900
com.deepin.dde.power battery-screen-black-delay 900
com.deepin.dde.power battery-sleep-delay 900
com.deepin.dde.power power-module-initialized true
com.deepin.dde.power lid-closed-sleep true
com.deepin.dde.power time-to-empty-low 1200

```

**Comment by jouyouyun** [comment]
Exec `gsettings set com.deepin.dde.daemon power false` and exec `killall dde-session-dae;/usr/lib/deepin-daemon/dde-session-daemon`, then open a terminal again, to exec `xset dpms force off`, wait 1 minute, check the system whether in suspend state.

**Comment by aiamuzz** [comment]
sure ...

`gsettings set com.deepin.dde.daemon power false`

```
killall dde-session-dae;/usr/lib/deepin-daemon/dde-session-daemon
dde-session-dae: no process found
<info> main.go:70: There already has a dde daemon running.

```

`xset dpms force off`

success ... system monitor switched off ... system perfect ... as should be !!!

what was the issue ?
the update messed something up ?

**Comment by aiamuzz** [comment]
oops ... sorry ... not perfect yet ...

setting 'password required to wake up the monitor' is 'enabled' ... i am not able to disable ... i click to disable but goes back to enable.

another thing ... though it is enabled ... there is no password prompt when monitor is woken after `xset dpms force off`

**Comment by aiamuzz** [comment]
key board shortcuts missing from the control-center ... music playing ... but music applet in control center not responding ... play, pause, next, volume ... nothing responding ... however volume control working from Dock Volume icon & Deepin-music control working in system tray

**Comment by aiamuzz** [comment]
oh ... seems like a there are 2 instances of control center the one which is not responsive(this is not hiding, it seems to be stuck) and another one which opens on top of this unresponsive control center  ... control center is possessed by an evil spirit ... 

do you want me to run any log's in this possessed state ? may not be able to recreate this issue after a reboot.

or shall i go ahead and reboot ...

**Comment by aiamuzz** [comment]
ok ... @jouyouyun 

Wen the 'fast screen off' was fixed with your set of commands ...

`gsettings set com.deepin.dde.daemon power false`
`killall dde-session-dae;/usr/lib/deepin-daemon/dde-session-daemon`

however it messed up the dock BIG time ... besides the dock the system was so slow and unresponsive ... i term this as the lowest point in my Deepin OS experience ... this was the first 'something is broken' feeling which i never had before ... Ubuntu had a lot of such 'something is broken' feelings ... but this is the first experience with Deepin OS ... i was really sad ... i didn't want to reinstall Deepin OS afresh ... i hate doing fresh installs !!!

However ... with nothing to lose ... i reversed the above commands ... by running the following ...

`gsettings set com.deepin.dde.daemon power true`
`killall dde-session-dae;/usr/lib/deepin-daemon/dde-session-daemon`

and Voila ... the system sprang back to its smooth self ...

However the 'fast screen off' suspending the whole machine is back ... 

something is broken pretty bad ... hope you guys find the issue ... let me know if you want to recreate this and record data(outputs) for your trouble shoot.

**Comment by jouyouyun** [comment]
Please exec:
```shell
gsettings set com.deepin.dde.daemon power true
gsettings set com.deepin.dde.power line-power-sleep-delay 0
gsettings set com.deepin.dde.power battery-sleep-delay 0
```
Then exec `killall dde-session-daemon;/usr/lib/deepin-daemon/dde-session-daemon -v > /tmp/dde.log 2>&1` and `xset dpms force off` in an other terminal. Check  the system whether in suspend state.

**Comment by aiamuzz** [comment]
ok ... strange ...

before trying the above commands ... i would like to bring the following to your attention ...

about ...
"however it messed up the dock BIG time ... besides the dock the system was so slow and unresponsive ... i term this as the lowest point in my Deepin OS experience ... this was the first 'something is broken' feeling which i never had before ... Ubuntu had a lot of such 'something is broken' feelings ... but this is the first experience with Deepin OS ... i was really sad ... i didn't want to reinstall Deepin OS afresh ... i hate doing fresh installs !!!"

I made a clone partition with deepin-clone of the above system state(where the dock was missing/unstable) ...

to test your new set of commands i thought let me boot into this cloned partition and run these command ... i didn't want to mess my daily work OS ...

BUT TO MY SURPRISE ... when i logged into the cloned root partition i see that the Deepin-Dock has suddenly started working normally ... and 'fast-screen-off' is working too with `gsettings set com.deepin.dde.daemon power false`

as reported yesterday the same state was highly unstable with the Dock acting nuts ... and today its working fine ... i can't explain that ... 

Do you want me to run the following commands ... and report back ... or do you want any logs from the current system state ... where `gsettings set com.deepin.dde.daemon power false` and 'fast screen off' is working and the Dock behaving normal ?


> ```
> gsettings set com.deepin.dde.daemon power true
> gsettings set com.deepin.dde.power line-power-sleep-delay 0
> gsettings set com.deepin.dde.power battery-sleep-delay 0
> 
> ```
> 
> ```
> killall dde-session-daemon;/usr/lib/deepin-daemon/dde-session-daemon -v > /tmp/dde.log 2>&1
> xset dpms force off
> ```

**Comment by aiamuzz** [comment]
yesterday with the following run ... 

`gsettings set com.deepin.dde.daemon power true`
`killall dde-session-dae;/usr/lib/deepin-daemon/dde-session-daemon`

'fast screen off' was suspending the whole machine instead of just the screen ...

today ... 'fast screen off' is working fine ... without doing anything !!!

GUYS I AM GOING CRAZY ... without explanation things are erratic one moment and the next moment they are working fine !!!

Deepin OS is possessed with 'evil spirits' ... it seriously needs 'exorcism'

FYI ... i installed the following last night ...

```
sudo apt-get install build-essential
sudo apt-get install fakeroot
sudo apt-get install qtcreator

```
did those installations somehow fix the 'fast screen off'(suspending) issue from yesterday ?

remember the 'fast screen off' problem started after running Deepin control center updates ...

only possible explanation is that installing things is messing 'fast screen off' and fixing it too ...

the BIG question is ... "What is causing things to mess and fixing it too ? "

I AM GOING CRAZY ...

**Comment by aiamuzz** [comment]
without running the following commands ...
```
gsettings set com.deepin.dde.power line-power-sleep-delay 0
gsettings set com.deepin.dde.power battery-sleep-delay 0

```

I am enclosing the log file after running the following commands ...

`killall dde-session-daemon;/usr/lib/deepin-daemon/dde-session-daemon -v > /tmp/dde.log 2>&1`
`xset dpms force off`

[dde.log](https://github.com/linuxdeepin/dde-control-center/files/1490192/dde.log)

hope this will help you probe things deeper ...

**Comment by jouyouyun** [comment]
Your 'fast screen off' work fine? So, it's meaningless to the log file.

**Comment by aiamuzz** [comment]
ok ...
so you don't want to probe further on why it was working one moment and fine the other ?

anyways ... i'll keep a watch if any other installations/updates break 'fast screen off' and append to this issue thread.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
