### ISSUE TITLE
{Feature Request} Shortcut to open dde-control-center

### ISSUE THREAD

**Issue by Ablablab** [linuxdeepin/dde-control-center#76]
Is there any way via code to invoke control center? Or a. Keyboard shortcut? I tried dde-control-center and dde-control-center show but It doesn't work on 15. 5

**Comment by GNOME-IS-LIFE** [comment]
dbus-send --print-reply --dest=com.deepin.dde.ControlCenter /com/deepin/dde/ControlCenter com.deepin.dde.ControlCenter.Show

**Comment by Ablablab** [comment]
Thank you, perfect!

**Comment by GNOME-IS-LIFE** [comment]
Welcome :smiley:

**Comment by AdrianoSiqueira** [comment]
@GNOME-IS-LIFE 
It worked! Thank you very much.

**Comment by caiodesign** [comment]
@GNOME-IS-LIFE 
Worked for me! Thank you mate!

**Comment by aareya** [comment]
Use the following instead

dbus-send --print-reply --dest=com.deepin.dde.ControlCenter /com/deepin/dde/ControlCenter com.deepin.dde.ControlCenter.Toggle

**Comment by alexwender1** [comment]
> dbus-send --print-reply --dest = com.deepin.dde.ControlCenter / com / deepin / dde / ControlCenter com.deepin.dde.ControlCenter.Show

@hualet Please, insert this shortcut into the system. I indicate the "Super+C" shortcut to trigger the Control Center.

[Other Request](https://github.com/linuxdeepin/developer-center/issues/1046)
