### ISSUE TITLE
Sound Tweak request : Auto Switching audio devices ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-control-center#77]
Hi,

my bluetooth headphone has to be manually selected from the audio device list (sound->advanced) ... an auto switching to bluetooth headphone would be ideal

Ideal preference order for auto switching ... highest to lowest ...

When a bluetooth/wireless Headphone is connected (wireless headphone)
When 3.5 mm audio is plugged in (wired headphone)
Native speaker default (when no external audio device is plugged in)

cheers

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
