### ISSUE TITLE
Minutes in time settings without leading zero when only one digit

### ISSUE THREAD

**Issue by magynhard** [linuxdeepin/dde-control-center#78]
When the current time in minutes has only one digit, the leading zero is missing in the time settings.

For example, when the time is 22:07, it looks like that (22:7 instead of 22:07)
![time_setting](https://user-images.githubusercontent.com/14541962/32984786-6a6f5a54-ccad-11e7-834e-e7d5f9071ae2.jpg)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
