### ISSUE TITLE
Mobile Wireless Networks ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-control-center#79]
Any WIP on squeezing in ...

'Mobile Wireless Networks' setting in between the Wired, Wireless and Hotspot settings ?

I have a built in 3G/LTE device embedded in my laptop and i am forced to use 'gnome-network-manager' to manage my Mobile Wireless device ...

cheers

**Comment by jouyouyun** [comment]
Deepin control center no 3G/LTE settings no longer, please install gnome network applet or using command `nmcli`.

**Comment by aiamuzz** [comment]
I did not understand ... will it be supported in future ?

**Comment by jouyouyun** [comment]
The mobile 4G  is enough

**Comment by aiamuzz** [comment]
you mean if a Mobile 4G is already implemented into the OS, if so the device should be detected by the control center ?
My device is a LTE/4G device ... shouldn't it be showing there then ?

**Comment by jouyouyun** [comment]
No, I mean that you using mobile hotspot or usb network sharing.

**Comment by aiamuzz** [comment]
I have this device inbuilt(pcie card)

`HP lt2523 Mobile Broadband Module`
Bus 001 Device 004: ID 03f0:421d Hewlett-Packard 

```
lsusb
Bus 002 Device 003: ID 0a5c:21e1 Broadcom Corp. HP Portable SoftSailing
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 002: ID 1d57:fa60 Xenta 
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 004: ID 03f0:421d Hewlett-Packard 
Bus 001 Device 003: ID 05c8:0341 Cheng Uei Precision Industry Co., Ltd (Foxlink) 
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

```
usb-devices
T:  Bus=01 Lev=02 Prnt=02 Port=04 Cnt=02 Dev#=  4 Spd=480 MxCh= 0
D:  Ver= 2.00 Cls=ef(misc ) Sub=02 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=03f0 ProdID=421d Rev=00.00
S:  Manufacturer=Novatel Wireless, Inc.
S:  Product=HP lt2523 Mobile Broadband Device
S:  SerialNumber=359789040033051
C:  #Ifs= 7 Cfg#= 1 Atr=e0 MxPwr=500mA
I:  If#= 0 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=ff Prot=ff Driver=option
I:  If#= 1 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=ff Prot=ff Driver=option
I:  If#= 2 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=ff Prot=ff Driver=option
I:  If#= 3 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=ff Prot=ff Driver=option
I:  If#= 4 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=ff Prot=ff Driver=option
I:  If#= 6 Alt= 0 #EPs= 1 Cls=02(commc) Sub=06 Prot=00 Driver=qmi_wwan
I:  If#= 7 Alt= 1 #EPs= 2 Cls=0a(data ) Sub=00 Prot=00 Driver=qmi_wwan

```

currently i am using gnome-network-manager applet as the screenshot suggests below ...

![deepinscreenshot_select-area_20171120130944](https://user-images.githubusercontent.com/3283676/33007345-5f9bb74c-cdf4-11e7-864d-073c6078ff27.png)

**Comment by aiamuzz** [comment]
this device does not show up in the Deepin Native Control Center

**Comment by jouyouyun** [comment]
Yes, we unsupported. You can report the bug to product disigner on [deepin bbs](bbs.deepin.org)

**Comment by aiamuzz** [comment]
thanks ... filed

https://bbs.deepin.org/forum.php?mod=viewthread&tid=148629&page=1&extra=#pid402851

**Comment by jouyouyun** [comment]
Great!
