### ISSUE TITLE
Most of the values are zero and I can't see any wireless networks icon

### ISSUE THREAD

**Issue by BenMaruchu** [linuxdeepin/dde-control-center#80]
I'm using dde on manjaro distro,
I have __dde-control-center v4.3.3__

can see any wireless networks (meaning the network button for wireless is not visible) on control center or on the dde-dock.

On the system information section in dde-control-center all values are either empty or zero. i.e memory, type and disk all have zero values, while processor and edition are empty.

**Comment by jouyouyun** [comment]
Exec the command `killall dde-session-daemon; /usr/lib/deepin-daemon/dde-session-daemon > /tmp/dde.log 2>&1` twice, then upload the file `/tmp/dde.log`.

**Comment by BenMaruchu** [comment]
@jouyouyun Thanks for your reply,

This is my dde.log file

[dde.log](https://github.com/linuxdeepin/dde-control-center/files/1490117/dde.log)

**Comment by BenMaruchu** [comment]
after the update of deepin-session-ui, and deepn-dock fixed the issue. Thanks
