### ISSUE TITLE
GUI for customizing touchpad gestures

### ISSUE THREAD

**Issue by aviwad** [linuxdeepin/dde-control-center#83]
Hello awesome Deepin developers!
I noticed Deepin's builtin touchpad gestures were stored in a `gestures.json` file in
`/usr/share/dde-daemon/gestures.json`
and could be made per user by copying the file (and editing it) in
`~/.config/deepin/dde-daemon/gestures.json`
So I was hoping, maybe you could include a GUI in the control center from which you could customize the gestures, giving options of the built-in things (listed in`/usr/share/dde-daemon/gesture_builtin.md`) and give an extra option of "custom command" letting you put any command to work when a certain gesture is swiped / pinched / clicked / tapped! That would exponentially make the user interface better than having to dig for some text file, copy it somewhere and manually edit it for touchpad gestures!

**Comment by jouyouyun** [comment]
In the plan.

**Comment by shaitaan** [comment]
what closes the app...!?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
