### ISSUE TITLE
Compilation error: fatal error: com_deepin_lastoresessionhelper.h: file or directory not found

### ISSUE THREAD

**Issue by 74cmonty** [linuxdeepin/dde-control-center#85]
Hi,
I'm compiling the source on Debian (Buster) and get this error:
`g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_MESSAGELOGCONTEXT -DQT_MESSAGELOGCONTEXT -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_SQL_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../frame -I. -I../../interfaces -I../../widgets -I../../modules -isystem /usr/include/libdtk-2.0/DWidget -isystem /usr/include/libdtk-2.0/DCore -isystem /usr/include/libdframeworkdbus-1.0 -isystem /usr/include/x86_64-linux-gnu/qt5/QGSettings -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o updatemodule.o ../../modules/update/updatemodule.cpp
In file included from ../../modules/update/updatemodule.h:34:0,
                 from ../../modules/update/updatemodule.cpp:26:
../../modules/update/updatework.h:37:10: fatal error: com_deepin_lastoresessionhelper.h: Datei oder Verzeichnis nicht gefunden
 #include <com_deepin_lastoresessionhelper.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:6268: die Regel für Ziel „updatemodule.o“ scheiterte
make[1]: *** [updatemodule.o] Fehler 1
make[1]: Verzeichnis „/home/dde-control-center/Build/frame“ wird verlassen
Makefile:46: die Regel für Ziel „sub-frame-make_first“ scheiterte
make: *** [sub-frame-make_first] Fehler 2
`
What's causing this error?

**Comment by sbwtw** [comment]
should install new version of [dde-qt-dbus-factory](https://github.com/linuxdeepin/dde-qt-dbus-factory)
