### ISSUE TITLE
QT apps could have scaling

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-control-center#88]
HOW TO REPRODUCE:
1. Go to "Control Center -> Display".
2. Under the section "display scaling" set a higher value.
3. Log out and in again.
4. Launch a QT based app.

RESULT:
- The scaling doesn't apply on the QT app.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
