### ISSUE TITLE
Can't change key binding for Super + Shift + <num>

### ISSUE THREAD

**Issue by ErikEklund** [linuxdeepin/dde-control-center#93]
I wanted to place the Screenshot keybinding on Super + Shift + 4, as I am used to this key combination from OS X.

It turns out that Super + Shift + < number > is already assign to "Move active window to workspace < number >". This is not shown in Keyboard -> Shortcuts, so there is no way to change this.

Suggestion: Add this keyboard shortcut to the control center so that you can change it.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
