### ISSUE TITLE
error during compilation

### ISSUE THREAD

**Issue by purvalpatel** [linuxdeepin/dde-control-center#96]
Error: com_deepin_lastoresessionhelper.h file not found during compilation,

below are the error logs ,
`In file included from ../../modules/update/updatemodule.h:34:0,
                 from ../../modules/update/updatemodule.cpp:26:
../../modules/update/updatework.h:37:10: fatal error: com_deepin_lastoresessionhelper.h: No such file or directory
 #include <com_deepin_lastoresessionhelper.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:6306: recipe for target 'updatemodule.o' failed
make[1]: *** [updatemodule.o] Error 1
make[1]: Leaving directory '/home/local/dde-control-center-master/Build/frame'
Makefile:46: recipe for target 'sub-frame-make_first' failed
make: *** [sub-frame-make_first] Error 2
`

**Comment by kirigayakazushin** [comment]
You need to compile dde-qt-dbus-factory first.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
