### ISSUE TITLE
Latest 15.6 control center too wide ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-control-center#99]
Hi,

the control center in Deepin 15.6 seemed a little too wide ...

![control center width](https://user-images.githubusercontent.com/3283676/41614045-045b783c-7415-11e8-999f-13a3da8075bd.png)

Also glad you have brought back the 'left category icons bar' to the control center ... i was wondering now that the left category icons bar is back ... is a continuous scroll'able settings needed ... seems confusing ... it made sense without the left bar but with the left bar seems more of a distraction ... 

anyways I had some time so i tested by reducing the width a little(6% reduction in width) and deleted the continuous scroll'able settings ... the right side shows ONLY sound settings.

Please note some minor tweaks around the Control Center header ... changed/moved elements are marked for comparison/illustration.

If the PM and Designer agree ...

Cheers.

**Comment by jouyouyun** [comment]
@sbwtw @kirigayakazushin

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
